<!DOCTYPE html>
<html lang="es"><head>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Edsaúl Emilio Pérez-Guerrero">
  <meta name="dcterms.date" content="2026-10-06">
  <title>Bioestadística avanzada – Modelos lineales I</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-992ed520baf37567c43dc1d740a96f26.css">
  <link rel="stylesheet" href="estilos.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Modelos lineales I</h1>
  <p class="subtitle">Correlación vs.&nbsp;regresión · Regresión lineal simple · ANOVA · Diagnóstico · Interpretación de coeficientes</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Edsaúl Emilio Pérez-Guerrero 
</div>
</div>
</div>

  <p class="date">2026-10-06</p>
</section>
<section id="objetivos-de-la-sesión" class="slide level2">
<h2>Objetivos de la sesión</h2>
<p>Al terminar la sesión, usted podrá:</p>
<ol type="1">
<li>Distinguir entre correlación y regresión.</li>
<li>Ajustar una <strong>regresión lineal simple</strong> en <code>R</code> y leer cada parte de su salida.</li>
<li>Construir e interpretar la <strong>tabla ANOVA</strong> de la regresión.</li>
<li><strong>Diagnosticar</strong> un modelo con la librería <code>performance</code>.</li>
<li><strong>Interpretar coeficientes</strong> y otros componentes de la <strong>regresión lineal simple</strong></li>
</ol>
</section>
<section id="ruta-del-tema-05-modelos-lineales" class="slide level2">
<h2>Ruta del tema 05: Modelos lineales</h2>
<table class="caption-top">
<colgroup>
<col style="width: 26%">
<col style="width: 37%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Contenido</th>
<th>¿Qué intentamos responder?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1 (hoy)</strong></td>
<td>Correlación vs.&nbsp;regresión, RLS, ANOVA, diagnóstico, interpretación</td>
<td>¿Cómo cambia <em>y</em> cuando cambia <em>x</em>?</td>
</tr>
<tr class="even">
<td>2</td>
<td>Regresión múltiple, variables categóricas (<em>dummy</em>), ajuste por covariables, selección de variables</td>
<td>¿Cuál es el efecto de <em>x</em> <strong>manteniendo constantes</strong> las demás?</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Interacciones y modificación del efecto</td>
<td>¿El efecto de <em>x</em> <strong>depende</strong> de <em>z</em>?</td>
</tr>
<tr class="even">
<td>4</td>
<td>Algoritmos para la selección de variables</td>
<td>¿Qué algoritmos podrían ayudar con la selección de variables</td>
</tr>
</tbody>
</table>
<p><br></p>
<div class="clave">
<p>Todo lo que veamos hoy es sienta las bases para las partes 2,3, 4.</p>
</div>
</section>
<section id="paquetes-y-datos" class="slide level2">
<h2>Paquetes y datos</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Instalar solo una vez</span></span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"ggplot2"</span>, <span class="st">"performance"</span>, <span class="st">"see"</span>, <span class="st">"readxl"</span>, <span class="st">"car"</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar librerías</span></span>
<span id="cb2-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)      <span class="co"># gráficos</span></span>
<span id="cb2-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)  <span class="co"># diagnóstico de modelos</span></span>
<span id="cb2-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see)          <span class="co"># gráficos de performance</span></span>
<span id="cb2-5"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Importar base de datos. Guardela en su carpeta de Bases</span></span>
<span id="cb2-7"><a aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Bases/sal_tension_arterial.csv"</span>)</span>
<span id="cb2-8"><a aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   80 obs. of  6 variables:
 $ Consumo_Sal     : num  1345 1517 1657 1726 1867 ...
 $ Tension_Arterial: num  106 115 110 102 112 ...
 $ Sexo            : chr  "Mujer" "Mujer" "Mujer" "Mujer" ...
 $ Comorbilidades  : int  0 1 1 0 1 0 1 1 1 1 ...
 $ Fuma            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Edad            : int  72 23 59 71 79 18 34 32 20 19 ...</code></pre>
</div>
</div>
<div class="small">
<p>80 pacientes: consumo de sal promedio de 10 días (mg/24 h) y tensión arterial sistólica (mmHg) <span class="citation" data-cites="perezguerrero2024bioestadistica">(<a href="#/referencias" role="doc-biblioref" onclick="">Pérez Guerrero 2024</a>)</span>.</p>
</div>
</section>
<section>
<section id="correlación-vs.-regresión" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>1. Correlación vs.&nbsp;regresión</h1>

</section>
<section id="diferencias-entre-correlación-y-regresión" class="slide level2">
<h2>Diferencias entre correlación y regresión</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="correlación">Correlación</h3>
<ul>
<li>¿Las dos variables <strong>varían juntas</strong>?</li>
<li>¿Qué tan <strong>fuerte</strong> y en qué <strong>dirección</strong>?</li>
<li>Relación <strong>simétrica</strong>: <span class="math inline">\(r_{xy} = r_{yx}\)</span></li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="regresión">Regresión</h3>
<ul>
<li>¿<strong>Cuánto cambia</strong> <em>y</em> cuando <em>x</em> cambia una unidad?</li>
<li>¿Qué valor de <em>y</em> <strong>predigo</strong> para un <em>x</em> dado?</li>
<li>Relación <strong>asimétrica</strong>: <span class="math inline">\(y \sim x \neq x \sim y\)</span></li>
</ul>
</div></div>
</section>
<section id="diferencias-entre-correlación-y-regresión-1" class="slide level2">
<h2>Diferencias entre correlación y regresión</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="correlación-1">Correlación</h3>
<ul>
<li><strong>Sin unidades</strong>, <span class="math inline">\(-1 \le r \le 1\)</span></li>
<li>No distingue variable dependiente de independiente</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="regresión-1">Regresión</h3>
<ul>
<li>Coeficientes <strong>en unidades</strong> de las variables</li>
<li>Exige definir <strong>respuesta</strong> (<em>y</em>) y <strong>predictor</strong> (<em>x</em>)</li>
</ul>
</div></div>
<div class="pregunta">
<p>¿El consumo de sal <strong>se asocia</strong> con la tensión arterial? ¿Qué técnica usaría? Y para ¿<strong>Cuántos mmHg</strong> aumenta la tensión por cada gramo de sal?</p>
</div>
</section>
<section id="correlación-en-r" class="slide level2">
<h2>Correlación en R</h2>
<div class="columns">
<div class="column" style="width:40%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficiente de correlación de Pearson con su prueba de hipótesis</span></span>
<span id="cb4-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Consumo_Sal, df<span class="sc">$</span>Tension_Arterial)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  df$Consumo_Sal and df$Tension_Arterial
t = 13.5, df = 78, p-value &lt;0.0000000000000002
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.75505 0.89194
sample estimates:
    cor 
0.83607 </code></pre>
</div>
</div>
</div><div class="column" style="width:60%;">
<ul>
<li><span class="math inline">\(r = 0.836\)</span>: asociación lineal <strong>positiva y fuerte</strong>.</li>
<li>Pero… ¿cuántos mmHg por mg de sal? <strong>La correlación no lo dice.</strong></li>
<li>Hasta el momento solo hemos indenficado que hay una relación positiva fuerte entre el consumo de sal y tensión arterial.</li>
<li>No sabemos cuanto afecta la tensión arterial el consumo de sal</li>
</ul>
</div></div>
</section>
<section id="la-regresión-sí-responde-cuánto" class="slide level2">
<h2>La regresión sí responde “¿cuánto?”</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># y ~ x : tensión arterial en función del consumo de sal</span></span>
<span id="cb6-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal, <span class="at">data =</span> df))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) Consumo_Sal 
   74.83910     0.02037 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># x ~ y : NO es el mismo modelo</span></span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Consumo_Sal <span class="sc">~</span> Tension_Arterial, <span class="at">data =</span> df))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept) Tension_Arterial 
       -1812.791           34.316 </code></pre>
</div>
</div>
<ul>
<li>Con <span class="math inline">\(y \sim x\)</span>: cada mg/24 h adicional → <strong>+0.0204 mmHg</strong> en promedio.</li>
<li>Con <span class="math inline">\(x \sim y\)</span> la pendiente <strong>no</strong> es <span class="math inline">\(1/0.0204 = 49.1\)</span>, es <span class="math inline">\(34.3\)</span>. La regresión <strong>no es simétrica</strong>: minimiza errores en la dirección de <em>y</em>.</li>
</ul>
</section>
<section id="cómo-se-conectan-r-y-beta_1" class="slide level2">
<h2>¿Cómo se conectan <span class="math inline">\(r\)</span> y <span class="math inline">\(\beta_1\)</span>?</h2>
<p><span class="math display">\[
\hat\beta_1 = r \cdot \frac{s_y}{s_x} \qquad\qquad R^2 = r^2 \;(\text{solo en regresión simple})
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a>r  <span class="ot">&lt;-</span> <span class="fu">cor</span>(df<span class="sc">$</span>Consumo_Sal, df<span class="sc">$</span>Tension_Arterial)</span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>sy <span class="ot">&lt;-</span> <span class="fu">sd</span>(df<span class="sc">$</span>Tension_Arterial)</span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a>sx <span class="ot">&lt;-</span> <span class="fu">sd</span>(df<span class="sc">$</span>Consumo_Sal)</span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a aria-hidden="true" tabindex="-1"></a>r <span class="sc">*</span> sy <span class="sc">/</span> sx   <span class="co"># pendiente de la regresión</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02037</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a>r<span class="sc">^</span><span class="dv">2</span>           <span class="co"># coeficiente de determinación</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.69901</code></pre>
</div>
</div>
<div class="clave">
<p>Si estandarizamos ambas variables (media 0, DE 1), la pendiente <strong>es</strong> <span class="math inline">\(r\)</span>. La correlación es una regresión “sin unidades”.</p>
</div>
</section>
<section id="correlación-no-implica-causalidad" class="slide level2">
<h2>Correlación no implica causalidad</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><img data-src="img/gato_correlacion.jpg" style="width:95.0%"></p>
</div><div class="column" style="width:50%;">
<p><img data-src="img/helados_tiburones.jpg" style="width:72.0%"></p>
</div></div>
</section>
<section id="y-la-regresión-tampoco-por-sí-sola" class="slide level2">
<h2>… y la regresión <strong>tampoco</strong>, por sí sola</h2>
<ul>
<li><code>lm()</code> estima <strong>asociaciones condicionales</strong>, no efectos causales.</li>
<li>La interpretación causal depende del <strong>diseño</strong> (aleatorización, temporalidad, control de confusores), no de la técnica.</li>
<li>En un estudio observacional escribimos: <em>“se <strong>asoció</strong> con…”</em>, <em>“por cada unidad… se <strong>espera en promedio</strong>…”</em> <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span>.</li>
</ul>
</section>
<section id="siempre-grafique.-cuarteto-de-anscombe" class="slide level2">
<h2>Siempre grafique. Cuarteto de Anscombe</h2>

<img data-src="Modelos_lineales_P1_files/figure-revealjs/anscombe-1.png" width="1200" class="r-stretch"><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Misma correlación en los 4 conjuntos</span></span>
<span id="cb14-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">cor</span>(anscombe<span class="sc">$</span>x1, anscombe<span class="sc">$</span>y1), <span class="fu">cor</span>(anscombe<span class="sc">$</span>x2, anscombe<span class="sc">$</span>y2),</span>
<span id="cb14-3"><a aria-hidden="true" tabindex="-1"></a>        <span class="fu">cor</span>(anscombe<span class="sc">$</span>x3, anscombe<span class="sc">$</span>y3), <span class="fu">cor</span>(anscombe<span class="sc">$</span>x4, anscombe<span class="sc">$</span>y4)), <span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.816 0.816 0.816 0.817</code></pre>
</div>
</div>
<div class="small">
<p>Mismo <span class="math inline">\(r\)</span>, misma recta (<span class="math inline">\(\hat y = 3 + 0.5x\)</span>), mismo <span class="math inline">\(R^2\)</span> <span class="citation" data-cites="anscombe1973graphs">(<a href="#/referencias" role="doc-biblioref" onclick="">Anscombe 1973</a>)</span>. Solo el conjunto 1 es apropiado para una regresión lineal.</p>
</div>
</section></section>
<section>
<section id="regresión-lineal-simple" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>2. Regresión lineal simple</h1>

</section>
<section id="el-problema" class="slide level2">
<h2>El problema</h2>
<blockquote>
<p>Un grupo de investigadores quiere evaluar el efecto del <strong>consumo diario de sal</strong> (mg/24 h) sobre la <strong>tensión arterial sistólica</strong> (mmHg) en 80 pacientes. Promediaron 10 días de mediciones <span class="citation" data-cites="perezguerrero2024bioestadistica">(<a href="#/referencias" role="doc-biblioref" onclick="">Pérez Guerrero 2024</a>)</span>.</p>
</blockquote>
</section>
<section id="antes-de-resolver-el-problema" class="slide level2">
<h2>Antes de resolver el problema</h2>
<p>Antes de ajustar una regresión, pregúntese:</p>
<ul>
<li>¿Mi objetivo <strong>requiere</strong> una regresión? ¿Explicar, predecir, ajustar?</li>
<li>¿Tengo claro quién es <em>y</em> (respuesta) y quién es <em>x</em> (predictor)?</li>
<li>¿Hay evidencia gráfica de relación <strong>lineal</strong>?</li>
<li>¿Las observaciones son <strong>independientes</strong>?</li>
<li>¿Existe plausibilidad biológica? <span class="citation" data-cites="perezguerrero2024bioestadistica">(<a href="#/referencias" role="doc-biblioref" onclick="">Pérez Guerrero 2024</a>)</span></li>
</ul>
<div class="clave">
<p>Si no puede responder estas preguntas, no haga una regresión. No es que no sea necesaria, simplemente puede que aún no sea tiempo.</p>
</div>
</section>
<section id="primero-el-gráfico" class="slide level2">
<h2>Primero, el gráfico</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Consumo_Sal, <span class="at">y =</span> Tension_Arterial)) <span class="sc">+</span></span>
<span id="cb16-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col =</span> <span class="st">"#F0A05B"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Consumo de sal (mg/24h)"</span>,</span>
<span id="cb16-5"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Tensión arterial sistólica (mmHg)"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Modelos_lineales_P1_files/figure-revealjs/fig-scatter-1.png" id="fig-scatter" width="1200" class="r-stretch quarto-figure-center"><p class="caption">
Figura&nbsp;1
</p></section>
<section id="el-modelo" class="slide level2">
<h2>El modelo</h2>
<p><span class="math display">\[
y_i = \underbrace{\beta_0 + \beta_1 x_i}_{\text{parte determinística}} + \underbrace{\varepsilon_i}_{\text{parte aleatoria}}, \qquad \varepsilon_i \sim N(0, \sigma^2)
\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th>Símbolo</th>
<th>Nombre</th>
<th>En el ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y_i\)</span></td>
<td>Variable dependiente (respuesta)</td>
<td>Tensión arterial (mmHg)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(x_i\)</span></td>
<td>Variable independiente (predictor)</td>
<td>Consumo de sal (mg/24 h)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_0\)</span></td>
<td>Intercepto</td>
<td>Tensión esperada cuando la sal = 0</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_1\)</span></td>
<td>Pendiente</td>
<td>Cambio esperado en <em>y</em> por 1 unidad de <em>x</em></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\varepsilon_i\)</span></td>
<td>Error</td>
<td>Lo que el modelo no explica</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\sigma^2\)</span></td>
<td>Varianza del error</td>
<td>Qué tan dispersos están los puntos alrededor de la recta</td>
</tr>
</tbody>
</table>
<div class="small">
<p>Los <span class="math inline">\(\beta\)</span> son <strong>parámetros</strong> poblacionales; con la muestra obtenemos <strong>estimaciones</strong> <span class="math inline">\(\hat\beta_0, \hat\beta_1\)</span> <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span>, <span class="citation" data-cites="perezguerrero2024bioestadistica">(<a href="#/referencias" role="doc-biblioref" onclick="">Pérez Guerrero 2024</a>)</span>.</p>
</div>
</section>
<section id="por-qué-esa-recta-y-no-otra" class="slide level2">
<h2>¿Por qué <em>esa</em> recta y no otra?</h2>

<img data-src="Modelos_lineales_P1_files/figure-revealjs/fig-lineas-1.png" id="fig-lineas" width="1200" class="r-stretch quarto-figure-center"><p class="caption">
Figura&nbsp;2
</p></section>
<section id="residuales" class="slide level2">
<h2>Residuales</h2>

<img data-src="img/residuales.png" class="quarto-figure quarto-figure-center r-stretch" style="width:80.0%"><p><span class="math display">\[
e_i = y_i - \hat y_i \qquad\text{(observado} - \text{predicho)}
\]</span></p>
</section>
<section id="mínimos-cuadrados-ordinarios-ols" class="slide level2">
<h2>Mínimos cuadrados ordinarios (OLS)</h2>
<p>La recta de mínimos cuadrados es la que <strong>minimiza la suma de los residuales al cuadrado</strong>:</p>
<p><span class="math display">\[
SSE = \sum_{i=1}^{n} e_i^2 = \sum_{i=1}^{n}\left[y_i - (\hat\beta_0 + \hat\beta_1 x_i)\right]^2
\]</span></p>
<p>Las soluciones son:</p>
<p><span class="math display">\[
\hat{\beta}_1 = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^n (x_i - \bar{x})^2}
\qquad\qquad
\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}
\]</span></p>
<p>En forma matricial (la que usa R y la que generaliza a regresión múltiple):</p>
<p><span class="math display">\[
\hat{\boldsymbol\beta} = (X^T X)^{-1} X^T \mathbf{y}
\]</span></p>
<div class="small">
<p>¿Por qué al cuadrado? Porque <span class="math inline">\(\sum e_i = 0\)</span> siempre en OLS: los errores positivos y negativos se cancelan. La recta pasa por <span class="math inline">\((\bar x, \bar y)\)</span>.</p>
</div>
</section>
<section id="componentes-de-la-regresión" class="slide level2">
<h2>Componentes de la regresión</h2>

<img data-src="img/componentes_regresion.png" class="quarto-figure quarto-figure-center r-stretch" style="width:85.0%"></section>
<section id="ajustar-el-modelo-lm" class="slide level2">
<h2>Ajustar el modelo: <code>lm()</code></h2>
<p>Estructura general: <code>lm(y ~ x, data = datos)</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Guardamos el modelo en un objeto para reutilizarlo</span></span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal, <span class="at">data =</span> df)</span>
<span id="cb17-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La función <code>lm</code> se utiliza para ajustar modelos lineales. Puede emplearse para realizar análisis de regresión, análisis de varianza de un solo estrato y análisis de covarianza.</p>
<p><strong>Uso</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(formula, data, subset, weights, na.action,</span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a>   <span class="at">method =</span> <span class="st">"qr"</span>, <span class="at">model =</span> <span class="cn">TRUE</span>, <span class="at">x =</span> <span class="cn">FALSE</span>, <span class="at">y =</span> <span class="cn">FALSE</span>, <span class="at">qr =</span> <span class="cn">TRUE</span>, </span>
<span id="cb18-3"><a aria-hidden="true" tabindex="-1"></a>   <span class="at">singular.ok =</span> <span class="cn">TRUE</span> <span class="at">contrasts =</span> <span class="cn">NULL</span>, <span class="at">offset =</span> <span class="cn">NULL</span>, ...)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="ajustar-el-modelo-lm-1" class="slide level2">
<h2>Ajustar el modelo: <code>lm()</code></h2>
<p>Estructura general: <code>lm(y ~ x, data = datos)</code></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Tension_Arterial ~ Consumo_Sal, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.988  -3.424  -0.313   3.531  13.142 

Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept) 74.83910    3.86125    19.4 &lt;0.0000000000000002 ***
Consumo_Sal  0.02037    0.00151    13.5 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.21 on 78 degrees of freedom
Multiple R-squared:  0.699, Adjusted R-squared:  0.695 
F-statistic:  181 on 1 and 78 DF,  p-value: &lt;0.0000000000000002</code></pre>
</div>
</div>
</section>
<section id="leer-la-salida-1-residuales" class="slide level2">
<h2>Leer la salida (1): residuales</h2>

<img data-src="img/Resultados_Residuales_final.png" class="quarto-figure quarto-figure-center r-stretch" style="width:62.0%"><ul>
<li>La <strong>mediana</strong> debe estar cerca de 0 (aquí −0.31).</li>
<li>1Q y 3Q deben estar a distancias similares de la mediana (≈ −3.4 y 3.5).</li>
<li>Mín. y Máx. aproximadamente simétricos (−16.0 y 13.1).</li>
<li>Es una <strong>primera mirada</strong>; el diagnóstico formal viene después.</li>
</ul>
</section>
<section id="leer-la-salida-2-coeficientes" class="slide level2">
<h2>Leer la salida (2): coeficientes</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="img/Resultados_Coeficientes1.png" class="quarto-figure quarto-figure-center" style="width:62.0%"></p>
</figure>
</div>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 74%">
</colgroup>
<thead>
<tr class="header">
<th>Columna</th>
<th>Qué es</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Estimate</code></td>
<td><span class="math inline">\(\hat\beta\)</span>: intercepto y pendiente</td>
</tr>
<tr class="even">
<td><code>Std. Error</code></td>
<td>Precisión de la estimación, <span class="math inline">\(SE(\hat\beta)\)</span></td>
</tr>
<tr class="odd">
<td><code>t value</code></td>
<td><span class="math inline">\(t = \hat\beta / SE(\hat\beta)\)</span>, prueba de <span class="math inline">\(H_0: \beta = 0\)</span> con <span class="math inline">\(n-2\)</span> gl</td>
</tr>
<tr class="even">
<td><code>Pr(&gt;|t|)</code></td>
<td>Valor <em>p</em> de esa prueba</td>
</tr>
</tbody>
</table>
</div></div>
</section>
<section id="intercepto-hatbeta_0" class="slide level2">
<h2>Intercepto <span class="math inline">\(\hat\beta_0\)</span></h2>

<img data-src="img/Resultados_Coeficientes2.png" class="quarto-figure quarto-figure-center r-stretch" style="width:58.0%"><ul>
<li><span class="math inline">\(\hat\beta_0 = 74.84\)</span> mmHg: tensión <strong>esperada</strong> cuando el consumo de sal es <strong>0 mg/24 h</strong>.</li>
<li>¿Tiene sentido clínico? El rango observado de sal es <strong>1 345 – 3 584 mg/24 h</strong>. El valor 0 está <strong>fuera</strong> de los datos → el intercepto es necesario para la recta, pero <strong>no se interpreta</strong> aquí.</li>
<li><span class="math inline">\(t = 74.84 / 3.86 = 19.38\)</span>; <span class="math inline">\(p &lt; 0.001\)</span>. Que el intercepto sea ≠ 0 rara vez es una pregunta de interés.</li>
</ul>
</section>
<section id="pendiente-hatbeta_1" class="slide level2">
<h2>Pendiente <span class="math inline">\(\hat\beta_1\)</span></h2>

<img data-src="img/Resultados_Coeficientes3.png" class="quarto-figure quarto-figure-center r-stretch" style="width:58.0%"><ul>
<li><span class="math inline">\(\hat\beta_1 = 0.02037\)</span>: por cada <strong>1 mg/24 h</strong> adicional de sal, la tensión sistólica es <strong>en promedio 0.020 mmHg mayor</strong>.</li>
<li><span class="math inline">\(t = 0.02037 / 0.001513 = 13.46\)</span>; <span class="math inline">\(p &lt; 0.001\)</span> → rechazamos <span class="math inline">\(H_0: \beta_1 = 0\)</span>.</li>
<li>¿Por qué nos importa que <span class="math inline">\(\beta_1 \neq 0\)</span>? Si <span class="math inline">\(\beta_1 = 0\)</span>, <em>x</em> no cambiaría a <em>y</em>: la recta sería horizontal.</li>
</ul>
</section>
<section id="intervalos-de-confianza-de-los-beta" class="slide level2">
<h2>Intervalos de confianza de los <span class="math inline">\(\beta\)</span></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modelo)             <span class="co"># IC 95 % por defecto</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 67.151944 82.526266
Consumo_Sal  0.017357  0.023383</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modelo, <span class="at">level =</span> <span class="fl">0.99</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                0.5 %    99.5 %
(Intercept) 64.644088 85.034122
Consumo_Sal  0.016374  0.024366</code></pre>
</div>
</div>
<ul>
<li>El IC 95 % de <span class="math inline">\(\beta_1\)</span> (0.0174 a 0.0234) <strong>no incluye 0</strong> → misma conclusión que la prueba <em>t</em>, pero con información de <strong>magnitud y precisión</strong>.</li>
<li>Piense: ¿concluiría igual con un IC de 0.00001 a 0.00002? Significancia estadística ≠ relevancia clínica.</li>
</ul>
</section>
<section id="error-estándar-residual-y-r2" class="slide level2">
<h2>Error estándar residual y <span class="math inline">\(R^2\)</span></h2>
<ul>
<li><strong>Residual standard error</strong> <span class="math inline">\(= \hat\sigma = 6.21\)</span> mmHg: dispersión típica de los puntos alrededor de la recta, <strong>en unidades de <em>y</em></strong>. Tiene <span class="math inline">\(n - 2 = 78\)</span> gl.</li>
<li><span class="math inline">\(R^2 = 0.699\)</span>: el modelo explica ≈ <strong>70 %</strong> de la variabilidad de la tensión arterial.</li>
<li><span class="math inline">\(R^2_{aj} = 0.695\)</span>: penaliza por número de predictores (clave en la parte 2, útil en regrsión múltiple).</li>
</ul>
<p><span class="math display">\[
R^2_{aj} = 1 - \frac{(1 - R^2)(n - 1)}{n - p - 1}
\]</span></p>
</section>
<section id="predicción-media-esperada-vs.-un-paciente-nuevo" class="slide level2">
<h2>Predicción: media esperada vs.&nbsp;un paciente nuevo</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a>nuevos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Consumo_Sal =</span> <span class="fu">c</span>(<span class="dv">2000</span>, <span class="dv">3000</span>))</span>
<span id="cb24-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a aria-hidden="true" tabindex="-1"></a><span class="co"># IC: dónde está la MEDIA de la tensión para ese consumo</span></span>
<span id="cb24-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> nuevos, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     fit    lwr    upr
1 115.58 113.51 117.65
2 135.95 133.93 137.97</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># IP: dónde caerá la tensión de UN paciente nuevo con ese consumo</span></span>
<span id="cb26-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> nuevos, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     fit    lwr    upr
1 115.58 103.04 128.12
2 135.95 123.42 148.48</code></pre>
</div>
</div>
<div class="clave">
<p>El intervalo de <strong>predicción</strong> siempre es más ancho: suma la incertidumbre de la recta <strong>más</strong> la variabilidad individual (<span class="math inline">\(\sigma^2\)</span>).</p>
</div>
</section>
<section id="predicción-visualmente" class="slide level2">
<h2>Predicción: visualmente</h2>

<img data-src="Modelos_lineales_P1_files/figure-revealjs/fig-bandas-1.png" id="fig-bandas" width="1200" class="r-stretch quarto-figure-center"><p class="caption">
Figura&nbsp;3
</p><div class="alerta">
<p><strong>No extrapole.</strong> Con 6 000 mg/24 h el modelo “predice” 197 mmHg, pero nunca observamos ese consumo.</p>
</div>
</section></section>
<section>
<section id="anova-en-regresión" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>3. ANOVA en regresión</h1>

</section>
<section id="la-idea-repartir-la-variabilidad" class="slide level2">
<h2>La idea: repartir la variabilidad</h2>
<p>¿Cuánto se aleja cada tensión arterial de la media? Esa distancia se <strong>descompone</strong> en dos:</p>
<p><span class="math display">\[
\underbrace{(y_i - \bar y)}_{\text{total}} = \underbrace{(\hat y_i - \bar y)}_{\text{explicada por la recta}} + \underbrace{(y_i - \hat y_i)}_{\text{residual}}
\]</span></p>
<div class="clave">
<p>Regresión y ANOVA hacen lo mismo: <strong>particionar la variabilidad</strong> en lo que el modelo explica y lo que no <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span>.</p>
</div>
</section>
<section id="anova-de-la-regresión" class="slide level2">
<h2>ANOVA de la regresión</h2>
<table class="caption-top">
<colgroup>
<col style="width: 32%">
<col style="width: 6%">
<col style="width: 29%">
<col style="width: 27%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Fuente de variación</th>
<th style="text-align: center;">df</th>
<th style="text-align: left;">Suma de cuadrados</th>
<th style="text-align: left;">Cuadrados medios</th>
<th style="text-align: left;">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Regresión</strong></td>
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: left;"><span class="math inline">\(RegSS = \sum(\hat{y}_i-\bar{y})^2\)</span></td>
<td style="text-align: left;"><span class="math inline">\(RegMS = \dfrac{\sum(\hat{y}_i-\bar{y})^2}{1}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(F = \dfrac{RegMS}{MSE}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Error</strong></td>
<td style="text-align: center;"><span class="math inline">\(n-2\)</span></td>
<td style="text-align: left;"><span class="math inline">\(SSE = \sum(y_i-\hat{y}_i)^2\)</span></td>
<td style="text-align: left;"><span class="math inline">\(MSE = \dfrac{\sum(y_i-\hat{y}_i)^2}{n-2}\)</span></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: center;"><span class="math inline">\(n-1\)</span></td>
<td style="text-align: left;"><span class="math inline">\(SST = \sum(y_i-\bar{y})^2\)</span></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</section>
<section id="la-descomposición-en-un-paciente" class="slide level2">
<h2>La descomposición, en un paciente</h2>

<img data-src="Modelos_lineales_P1_files/figure-revealjs/fig-descomposicion-1.png" id="fig-descomposicion" width="1200" class="r-stretch quarto-figure-center"><p class="caption">
Figura&nbsp;4
</p></section>
<section id="podemos-calcular-con-anova" class="slide level2">
<h2>Podemos calcular con <code>anova()</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Tension_Arterial
            Df Sum Sq Mean Sq F value              Pr(&gt;F)    
Consumo_Sal  1   6992    6992     181 &lt;0.0000000000000002 ***
Residuals   78   3011      39                                
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>

<img data-src="img/Resultados_Coeficientes5.png" class="quarto-figure quarto-figure-center r-stretch" style="width:45.0%"></section>
<section id="también-podemos-calcular-con-summary" class="slide level2">
<h2>También podemos calcular con <code>summary()</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Tension_Arterial ~ Consumo_Sal, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.988  -3.424  -0.313   3.531  13.142 

Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept) 74.83910    3.86125    19.4 &lt;0.0000000000000002 ***
Consumo_Sal  0.02037    0.00151    13.5 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.21 on 78 degrees of freedom
Multiple R-squared:  0.699, Adjusted R-squared:  0.695 
F-statistic:  181 on 1 and 78 DF,  p-value: &lt;0.0000000000000002</code></pre>
</div>
</div>
</section>
<section id="todo-está-conectado" class="slide level2">
<h2>Todo está conectado</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">En <code>anova()</code></th>
<th style="text-align: left;">En <code>summary()</code></th>
<th style="text-align: left;">Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(SSR/SST = 6992.3/10003.2\)</span></td>
<td style="text-align: left;">Multiple R-squared: 0.699</td>
<td style="text-align: left;"><strong>SSR:</strong> suma de cuadrados de la regresión; <strong>SST:</strong> suma de cuadrados total. Su cociente corresponde a <span class="math inline">\(R^2\)</span>, la proporción de variabilidad explicada por el modelo.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\sqrt{MSE} = \sqrt{38.6}\)</span></td>
<td style="text-align: left;">Residual standard error: 6.213</td>
<td style="text-align: left;"><strong>MSE:</strong> cuadrado medio del error (<em>Mean Squared Error</em>). Su raíz estima la desviación estándar de los residuos (<span class="math inline">\(\sigma\)</span>).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(F = 181.1\)</span> con 1 y 78 gl</td>
<td style="text-align: left;">F-statistic: 181.1 on 1 and 78 DF</td>
<td style="text-align: left;"><strong>F:</strong> estadístico F, compara la variabilidad explicada por el modelo con la variabilidad residual. <strong>gl/DF:</strong> grados de libertad (<em>degrees of freedom</em>).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(F = t^2 = 13.46^2\)</span></td>
<td style="text-align: left;"><em>t</em> de la pendiente = 13.46</td>
<td style="text-align: left;">En regresión lineal simple, <span class="math inline">\(F=t^2\)</span>. Ambas pruebas evalúan <span class="math inline">\(H_0:\beta_1=0\)</span>.</td>
</tr>
</tbody>
</table>
<aside class="notes">
<ul>
<li>SSR (Suma de Cuadrados de la Regresión o Sum of Squares Regression)</li>
<li>SST (Suma Total de Cuadrados, o Total Sum of Squares) en regresión lineal es la medida de la variabilidad total de la variable dependiente (Y) alrededor de su propia media</li>
<li>Error Cuadrático Medio o Mean Squared Error (MSE) es una métrica que mide el promedio de los errores al cuadrado entre los valores reales y los valores pronosticados por un modelo de regresión</li>
</ul>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="anova-como-comparación-de-modelos-anidados" class="slide level2">
<h2>ANOVA como comparación de modelos anidados</h2>
<p>El <em>F</em> global compara <strong>dos modelos</strong>:</p>
<ul>
<li>Modelo nulo: <span class="math inline">\(y_i = \beta_0 + \varepsilon_i\)</span> (solo la media, <span class="math inline">\(\hat\beta_0 = \bar y\)</span>)</li>
<li>Modelo completo: <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \varepsilon_i\)</span></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a aria-hidden="true" tabindex="-1"></a>modelo_nulo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> df)   <span class="co"># solo intercepto</span></span>
<span id="cb32-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_nulo, modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Tension_Arterial ~ 1
Model 2: Tension_Arterial ~ Consumo_Sal
  Res.Df   RSS Df Sum of Sq   F              Pr(&gt;F)    
1     79 10003                                         
2     78  3011  1      6992 181 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="anova-como-comparación-de-modelos-anidados-1" class="slide level2">
<h2>ANOVA como comparación de modelos anidados</h2>
<p><span class="math display">\[
F = \frac{(SSE_{nulo} - SSE_{completo}) / (gl_{nulo} - gl_{completo})}{SSE_{completo} / gl_{completo}}
\]</span></p>
<div class="clave">
<p>Esta es <strong>la</strong> herramienta para comparar modelos en la parte 2: ¿agregar una variable reduce significativamente el error?</p>
</div>
</section>
<section id="qué-anova-está-pidiendo-r" class="slide level2">
<h2>¿Qué ANOVA está pidiendo R?</h2>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Función</th>
<th>Tipo de SC</th>
<th>Qué prueba</th>
<th>Cuándo importa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>summary(modelo)</code> (última línea)</td>
<td>—</td>
<td><em>F</em> global: todos los <span class="math inline">\(\beta = 0\)</span></td>
<td>Siempre</td>
</tr>
<tr class="even">
<td><code>anova(modelo)</code></td>
<td><strong>Secuencial (tipo I)</strong></td>
<td>Cada término <strong>en el orden</strong> en que entra</td>
<td>Múltiple: el orden cambia el resultado</td>
</tr>
<tr class="odd">
<td><code>anova(m0, m1)</code></td>
<td>Modelos anidados</td>
<td>¿El modelo grande mejora al pequeño?</td>
<td>Selección y comparación de modelos</td>
</tr>
<tr class="even">
<td><code>car::Anova(modelo, type = 2)</code></td>
<td><strong>Tipo II</strong></td>
<td>Cada término ajustado por los demás</td>
<td>Múltiple sin interacciones</td>
</tr>
<tr class="odd">
<td><code>car::Anova(modelo, type = 3)</code></td>
<td><strong>Tipo III</strong></td>
<td>Cada término ajustado por todo (incl.&nbsp;interacciones)</td>
<td>Con interacciones (requiere contrastes adecuados)</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(modelo, <span class="at">type =</span> <span class="dv">2</span>)   <span class="co"># con 1 predictor: idéntico a anova(modelo)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: Tension_Arterial
            Sum Sq Df F value              Pr(&gt;F)    
Consumo_Sal   6992  1     181 &lt;0.0000000000000002 ***
Residuals     3011 78                                
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="small">
<p>Con un solo predictor todas coinciden. En la parte 2 veremos cómo divergen.</p>
</div>
</section>
<section id="el-anova-clásico-también-es-una-regresión" class="slide level2">
<h2>El ANOVA “clásico” también es una regresión</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Fuma: 0 = no fuma, 1 = ex-fumador, 2 = fumador</span></span>
<span id="cb36-2"><a aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Fuma_f <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Fuma, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No fuma"</span>, <span class="st">"Ex-fumador"</span>, <span class="st">"Fumador"</span>))</span>
<span id="cb36-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(Tension_Arterial <span class="sc">~</span> Fuma_f, <span class="at">data =</span> df))   <span class="co"># ANOVA de una vía</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value              Pr(&gt;F)    
Fuma_f       2   6251    3126    64.2 &lt;0.0000000000000002 ***
Residuals   77   3752      49                                
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Fuma_f, <span class="at">data =</span> df))      <span class="co"># misma tabla con lm()</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Tension_Arterial
          Df Sum Sq Mean Sq F value              Pr(&gt;F)    
Fuma_f     2   6251    3126    64.2 &lt;0.0000000000000002 ***
Residuals 77   3752      49                                
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="small">
<p>ANOVA de una vía, prueba <em>t</em> y regresión son casos del <strong>modelo lineal general</strong>. Cómo se codifica <code>Fuma_f</code> dentro de <code>lm()</code> (variables <em>dummy</em>) es tema de la parte 2.</p>
</div>
</section></section>
<section>
<section id="diagnóstico-del-modelo" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>4. Diagnóstico del modelo</h1>

</section>
<section id="supuestos-lo-que-f-t-e-ic-dan-por-hecho" class="slide level2">
<h2>Supuestos: lo que <em>F</em>, <em>t</em> e IC dan por hecho</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Supuesto</th>
<th>Qué significa</th>
<th>Si se viola…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>L</strong>inealidad</td>
<td>La media de <em>y</em> cambia linealmente con <em>x</em></td>
<td><span class="math inline">\(\hat\beta\)</span> sesgados; el modelo está mal especificado</td>
</tr>
<tr class="even">
<td><strong>I</strong>ndependencia</td>
<td>Los errores no se relacionan entre sí (no mediciones repetidas, no clusters)</td>
<td>EE subestimados, <em>p</em> demasiado pequeños</td>
</tr>
<tr class="odd">
<td><strong>N</strong>ormalidad</td>
<td>Los <strong>residuales</strong> (no las variables) son ≈ normales</td>
<td>IC y <em>p</em> poco fiables con <em>n</em> pequeña</td>
</tr>
<tr class="even">
<td><strong>E</strong>qual variance (homocedasticidad)</td>
<td>Varianza del error constante a lo largo de <span class="math inline">\(\hat y\)</span></td>
<td>EE incorrectos</td>
</tr>
<tr class="odd">
<td>Sin observaciones <strong>influyentes</strong></td>
<td>Ningún punto “jala” la recta por sí solo</td>
<td>Coeficientes dependientes de 1–2 pacientes</td>
</tr>
</tbody>
</table>
<div class="small">
<p>La normalidad es el supuesto menos crítico con muestras grandes; linealidad e independencia, los más <span class="citation" data-cites="schmidt2018linear fox2016applied">(<a href="#/referencias" role="doc-biblioref" onclick="">Schmidt y Finan 2018</a>; <a href="#/referencias" role="doc-biblioref" onclick="">Fox 2016</a>)</span>.</p>
</div>
</section>
<section id="diagnóstico-clásico-plotmodelo" class="slide level2">
<h2>Diagnóstico clásico: <code>plot(modelo)</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))   <span class="co"># 4 gráficos en una ventana</span></span>
<span id="cb40-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>

<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<img data-src="Modelos_lineales_P1_files/figure-revealjs/plot-base-1.png" width="1200" class="r-stretch"></section>
<section id="diagnóstico-con-performancecheck_model" class="slide level2">
<h2>Diagnóstico con <code>performance::check_model()</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="diagnóstico-con-performancecheck_model-output" class="slide level2 output-location-slide"><h2>Diagnóstico con <code>performance::check_model()</code></h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Modelos_lineales_P1_files/figure-revealjs/check-model-1.png" width="1500"></p>
</figure>
</div>
</div>
</div></section><section id="cómo-leer-check_model" class="slide level2">
<h2>Cómo leer <code>check_model()</code></h2>
<table class="caption-top">
<colgroup>
<col style="width: 27%">
<col style="width: 29%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th>Panel</th>
<th>Pregunta</th>
<th>Lo que queremos ver</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Posterior predictive check</strong></td>
<td>¿Los datos simulados por el modelo se parecen a los observados?</td>
<td>Líneas azules que envuelven la verde</td>
</tr>
<tr class="even">
<td><strong>Linearity</strong></td>
<td>¿Hay curvatura en residuales vs.&nbsp;ajustados?</td>
<td>Línea de referencia <strong>plana y horizontal</strong></td>
</tr>
<tr class="odd">
<td><strong>Homogeneity of variance</strong></td>
<td>¿La dispersión cambia con <span class="math inline">\(\hat y\)</span>?</td>
<td>Línea <strong>plana y horizontal</strong></td>
</tr>
<tr class="even">
<td><strong>Influential observations</strong></td>
<td>¿Algún punto fuera de las curvas de Cook?</td>
<td>Todos los puntos <strong>dentro</strong> de las líneas punteadas</td>
</tr>
<tr class="odd">
<td><strong>Normality of residuals</strong></td>
<td>¿Los residuales siguen la distribución normal?</td>
<td>Puntos sobre la línea (bandas incluyen la línea)</td>
</tr>
</tbody>
</table>
<div class="small">
<p>En regresión múltiple aparece además el panel de <strong>colinealidad (VIF)</strong>, que veremos en la parte 2 <span class="citation" data-cites="ludecke2021performance">(<a href="#/referencias" role="doc-biblioref" onclick="">Lüdecke et&nbsp;al. 2021</a>)</span>.</p>
</div>
</section>
<section id="pruebas-individuales-con-performance" class="slide level2">
<h2>Pruebas individuales con <code>performance</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(modelo)           <span class="co"># Shapiro-Wilk sobre residuales estudentizados</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.719).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(modelo)  <span class="co"># Breusch-Pagan</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.859).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_autocorrelation</span>(modelo)     <span class="co"># Durbin-Watson (independencia)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Residuals appear to be independent and not autocorrelated (p = 0.650).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_outliers</span>(modelo)            <span class="co"># distancia de Cook</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: No outliers detected.
- Based on the following method and threshold: cook (0.7).
- For variable: (Whole model)</code></pre>
</div>
</div>
<div class="alerta">
<p>Las pruebas <strong>complementan</strong> a los gráficos, no los sustituyen. Con <em>n</em> grande detectan desviaciones irrelevantes; con <em>n</em> pequeña no detectan problemas serios.</p>
</div>
</section>
<section id="apalancamiento-e-influencia-con-base-r" class="slide level2">
<h2>Apalancamiento e influencia (con base R)</h2>
<ul>
<li><strong>Apalancamiento</strong> (<em>leverage</em>, <span class="math inline">\(h_{ii}\)</span>): qué tan lejos está <span class="math inline">\(x_i\)</span> del resto. Regla: <span class="math inline">\(h_{ii} &gt; 2(p+1)/n\)</span>.</li>
<li><strong>Distancia de Cook</strong> (<span class="math inline">\(D_i\)</span>): cuánto cambian <strong>todos</strong> los <span class="math inline">\(\hat\beta\)</span> si quitamos al paciente <em>i</em>. Reglas: <span class="math inline">\(D_i &gt; 4/n\)</span> (sensible) o <span class="math inline">\(D_i &gt; F_{0.5;\,p+1,\,n-p-1} \approx 0.7\)</span> (la que usa <code>check_outliers()</code>).</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a aria-hidden="true" tabindex="-1"></a>h  <span class="ot">&lt;-</span> <span class="fu">hatvalues</span>(modelo)</span>
<span id="cb51-2"><a aria-hidden="true" tabindex="-1"></a>cd <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(modelo)</span>
<span id="cb51-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(h <span class="sc">&gt;</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">2</span> <span class="sc">/</span> <span class="fu">nrow</span>(df))   <span class="co"># pacientes con apalancamiento alto</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(cd)                     <span class="co"># Cook más grande</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.091438</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(cd <span class="sc">&gt;</span> <span class="dv">4</span> <span class="sc">/</span> <span class="fu">nrow</span>(df))      <span class="co"># pacientes que superan 4/n</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<div class="small">
<p>Apalancamiento alto ≠ influyente. En regresión simple, los pacientes con consumos extremos siempre tienen <span class="math inline">\(h_{ii}\)</span> alto; lo que importa es si además <strong>mueven</strong> la recta (Cook) <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span>.</p>
</div>
</section>
<section id="índices-de-desempeño-del-modelo" class="slide level2">
<h2>Índices de desempeño del modelo</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">model_performance</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC   |  AICc |   BIC |    R2 | R2 (adj.) |  RMSE | Sigma
---------------------------------------------------------
523.3 | 523.6 | 530.4 | 0.699 |     0.695 | 6.135 | 6.213</code></pre>
</div>
</div>
<ul>
<li><code>R2</code>, <code>R2 (adj.)</code>: proporción de varianza explicada.</li>
<li><code>RMSE</code> / <code>Sigma</code>: error típico de predicción (mmHg).</li>
<li><code>AIC</code>, <code>BIC</code>: útiles para <strong>comparar</strong> modelos (menor = mejor); los usaremos en la parte 2 con <code>compare_performance()</code>.</li>
</ul>
</section>
<section id="un-modelo-que-no-cumple" class="slide level2">
<h2>Un modelo que <strong>no</strong> cumple</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb59-2"><a aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb59-3"><a aria-hidden="true" tabindex="-1"></a>x_sim <span class="ot">&lt;-</span> <span class="fu">runif</span>(n_sim, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb59-4"><a aria-hidden="true" tabindex="-1"></a>y_sim <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> x_sim <span class="sc">+</span> <span class="fu">rnorm</span>(n_sim, <span class="at">sd =</span> <span class="fl">0.5</span> <span class="sc">+</span> <span class="fl">0.8</span> <span class="sc">*</span> x_sim)  <span class="co"># la varianza crece con x</span></span>
<span id="cb59-5"><a aria-hidden="true" tabindex="-1"></a>x_sim <span class="ot">&lt;-</span> <span class="fu">c</span>(x_sim, <span class="fl">9.5</span>)        <span class="co"># agregamos un paciente muy atípico</span></span>
<span id="cb59-6"><a aria-hidden="true" tabindex="-1"></a>y_sim <span class="ot">&lt;-</span> <span class="fu">c</span>(y_sim, <span class="sc">-</span><span class="dv">15</span>)</span>
<span id="cb59-7"><a aria-hidden="true" tabindex="-1"></a>malo  <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> x_sim, <span class="at">y =</span> y_sim)</span>
<span id="cb59-8"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-9"><a aria-hidden="true" tabindex="-1"></a>modelo_malo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> malo)</span>
<span id="cb59-10"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(modelo_malo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Heteroscedasticity (non-constant error variance) detected (p &lt; .001).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(modelo_malo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p &lt; .001).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_outliers</span>(modelo_malo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>1 outlier detected: case 101.
- Based on the following method and threshold: cook (0.7).
- For variable: (Whole model).</code></pre>
</div>
</div>
</section>
<section id="un-modelo-que-no-cumple-check_model" class="slide level2">
<h2>Un modelo que <strong>no</strong> cumple: <code>check_model()</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(modelo_malo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Modelos_lineales_P1_files/figure-revealjs/check-model-malo-1.png" width="1500" class="r-stretch"><aside class="notes">
<p>Señalar: forma de embudo en homogeneidad, un punto fuera de las curvas de Cook, colas en el QQ.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="y-si-el-modelo-no-cumple" class="slide level2">
<h2>¿Y si el modelo no cumple?</h2>
<table class="caption-top">
<colgroup>
<col style="width: 31%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th>Problema</th>
<th>Opciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No linealidad</td>
<td>Transformar <em>x</em> (log, raíz), términos polinomiales, splines</td>
</tr>
<tr class="even">
<td>Heterocedasticidad</td>
<td>Transformar <em>y</em> (log), errores estándar robustos (<code>sandwich</code>), mínimos cuadrados ponderados</td>
</tr>
<tr class="odd">
<td>No normalidad</td>
<td>Con <em>n</em> grande suele bastar; <em>bootstrap</em> de coeficientes; revisar si es por atípicos</td>
</tr>
<tr class="even">
<td>No independencia</td>
<td>Modelos mixtos, GEE (medidas repetidas, clusters)</td>
</tr>
<tr class="odd">
<td>Observaciones influyentes</td>
<td>Verificar captura; analizar <strong>con y sin</strong> ellas y reportar ambos; <strong>nunca</strong> eliminar solo por “no ajustar”</td>
</tr>
</tbody>
</table>
<div class="clave">
<p>Diagnosticar no es un trámite: es parte del análisis y debe <strong>reportarse</strong> en métodos.</p>
</div>
</section></section>
<section>
<section id="interpretación-de-los-coeficientes" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>5. Interpretación de los coeficientes</h1>

</section>
<section id="plantilla-de-interpretación" class="slide level2">
<h2>Plantilla de interpretación</h2>
<blockquote>
<p>Por cada <strong>[1 unidad de <em>x</em>]</strong> adicional, <strong>[<em>y</em>]</strong> fue en promedio <strong>[<span class="math inline">\(\hat\beta_1\)</span> unidades de <em>y</em>]</strong> mayor/menor (IC 95 %: <strong>[li, ls]</strong>; <em>p</em> = <strong>[valor]</strong>).</p>
</blockquote>
<p>Siempre responda:</p>
<ol type="1">
<li>¿En qué <strong>unidades</strong> están <em>x</em> e <em>y</em>?</li>
<li>¿Es <strong>clínicamente relevante</strong> “1 unidad” de <em>x</em>? ¿Conviene reescalar?</li>
<li>¿El intercepto tiene <strong>sentido</strong> dentro del rango observado?</li>
<li>¿El IC incluye 0? ¿Qué tan <strong>amplio</strong> es?</li>
</ol>
</section>
<section id="ejemplo-1.-sal-reescalar-para-que-tenga-sentido" class="slide level2">
<h2>Ejemplo 1. Sal: reescalar para que tenga sentido</h2>
<p>1 mg de sal es clínicamente irrelevante. Expresemos la sal en <strong>gramos</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Sal_g <span class="ot">&lt;-</span> df<span class="sc">$</span>Consumo_Sal <span class="sc">/</span> <span class="dv">1000</span>     <span class="co"># mg -&gt; g</span></span>
<span id="cb66-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a aria-hidden="true" tabindex="-1"></a>modelo_g <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Sal_g, <span class="at">data =</span> df)</span>
<span id="cb66-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(modelo_g)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       Sal_g 
     74.839      20.370 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modelo_g)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept) 67.152 82.526
Sal_g       17.357 23.383</code></pre>
</div>
</div>
<div class="clave">
<p>Por cada <strong>gramo/24 h</strong> adicional de sal, la tensión sistólica fue en promedio <strong>20.4 mmHg</strong> mayor (IC 95 %: 17.4 a 23.4). Mismo modelo, mismo <em>p</em>, mismo <span class="math inline">\(R^2\)</span>: solo cambian las unidades de <span class="math inline">\(\hat\beta_1\)</span>.</p>
</div>
</section>
<section id="ejemplo-1b.-centrar-para-interpretar-el-intercepto" class="slide level2">
<h2>Ejemplo 1b. Centrar para interpretar el intercepto</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Restamos la media: ahora 0 = consumo promedio (2 510 mg/24h)</span></span>
<span id="cb70-2"><a aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Sal_c <span class="ot">&lt;-</span> df<span class="sc">$</span>Consumo_Sal <span class="sc">-</span> <span class="fu">mean</span>(df<span class="sc">$</span>Consumo_Sal)</span>
<span id="cb70-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Sal_c, <span class="at">data =</span> df))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       Sal_c 
  125.95987     0.02037 </code></pre>
</div>
</div>
<ul>
<li><strong>Pendiente idéntica</strong> (0.0204).</li>
<li>El intercepto ahora es <strong>126.0 mmHg</strong> = tensión esperada para un paciente con consumo <strong>promedio</strong> de sal. ¡Ahora sí se interpreta!</li>
<li>En una regresión lineal simple centrar X cambia la interpretación del intercepto, pero no cambia la pendiente.</li>
<li>Estaremos viendo el intercepto la tensión arterial para la media del consumo de sal.</li>
</ul>
<div class="small">
<p>Centrar será muy importante en las interacciones.</p>
</div>
</section>
<section id="ejemplo-2.-capacidad-pulmonar-y-estatura" class="slide level2">
<h2>Ejemplo 2. Capacidad pulmonar y estatura</h2>
<p><code>LungCapData</code>: 725 personas de 3 a 19 años (Mike Marin, <em>statslectures</em>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a aria-hidden="true" tabindex="-1"></a>lung <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Bases/LungCapData.xls"</span>)</span>
<span id="cb72-2"><a aria-hidden="true" tabindex="-1"></a>lung<span class="sc">$</span>Height_cm <span class="ot">&lt;-</span> lung<span class="sc">$</span>Height <span class="sc">*</span> <span class="fl">2.54</span>            <span class="co"># pulgadas -&gt; cm</span></span>
<span id="cb72-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a aria-hidden="true" tabindex="-1"></a>modelo_lung <span class="ot">&lt;-</span> <span class="fu">lm</span>(LungCap <span class="sc">~</span> Height_cm, <span class="at">data =</span> lung)</span>
<span id="cb72-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">coef</span>(modelo_lung), <span class="fu">confint</span>(modelo_lung))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %    97.5 %
(Intercept) -13.99683 -14.71823 -13.27543
Height_cm     0.13274   0.12839   0.13709</code></pre>
</div>
</div>
<ul>
<li><strong>Pendiente</strong>: por cada cm adicional de estatura, la capacidad pulmonar fue en promedio <strong>0.133 L</strong> mayor (IC 95 %: 0.128 a 0.137); por cada 10 cm, <strong>1.33 L</strong>.</li>
<li><strong>Intercepto</strong> = −14.0 L: capacidad pulmonar “a 0 cm de estatura”. <strong>Imposible</strong>; la estatura mínima observada es 115 cm.</li>
</ul>
</section>
<section id="ejemplo-2b.-centrar-la-estatura" class="slide level2">
<h2>Ejemplo 2b. Centrar la estatura</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a aria-hidden="true" tabindex="-1"></a>lung<span class="sc">$</span>Height_c <span class="ot">&lt;-</span> lung<span class="sc">$</span>Height_cm <span class="sc">-</span> <span class="fu">mean</span>(lung<span class="sc">$</span>Height_cm)   <span class="co"># 0 = 164.7 cm</span></span>
<span id="cb74-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">coef</span>(<span class="fu">lm</span>(LungCap <span class="sc">~</span> Height_c, <span class="at">data =</span> lung)),</span>
<span id="cb74-3"><a aria-hidden="true" tabindex="-1"></a>      <span class="fu">confint</span>(<span class="fu">lm</span>(LungCap <span class="sc">~</span> Height_c, <span class="at">data =</span> lung)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      2.5 %  97.5 %
(Intercept) 7.86315 7.78356 7.94274
Height_c    0.13274 0.12839 0.13709</code></pre>
</div>
</div>
<ul>
<li>Intercepto = <strong>7.86 L</strong>: capacidad pulmonar esperada para alguien de <strong>estatura promedio</strong> (164.7 cm).</li>
<li>La pendiente no cambia.</li>
</ul>
<div class="pregunta">
<p>¿Qué pasaría con la interpretación si centráramos en 150 cm en lugar de la media?</p>
</div>
</section>
<section id="ejemplo-3.-capacidad-pulmonar-y-edad-cuidado-con-extrapolar" class="slide level2">
<h2>Ejemplo 3. Capacidad pulmonar y edad: cuidado con extrapolar</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a aria-hidden="true" tabindex="-1"></a>modelo_edad <span class="ot">&lt;-</span> <span class="fu">lm</span>(LungCap <span class="sc">~</span> Age, <span class="at">data =</span> lung)</span>
<span id="cb76-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">coef</span>(modelo_edad), <span class="fu">confint</span>(modelo_edad))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      2.5 %  97.5 %
(Intercept) 1.14686 0.78655 1.50717
Age         0.54485 0.51705 0.57265</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(lung<span class="sc">$</span>Age)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3 19</code></pre>
</div>
</div>
<ul>
<li>Por cada año de edad, la capacidad pulmonar fue en promedio <strong>0.545 L</strong> mayor (IC 95 %: 0.517 a 0.573).</li>
<li>Válido <strong>entre 3 y 19 años</strong>. A los 60 años el modelo “predice” 33.8 L. ¿Tiene sentido?</li>
</ul>
<div class="alerta">
<p>La linealidad solo se sostiene <strong>dentro</strong> del rango observado. En adultos la capacidad pulmonar disminuye con la edad.</p>
</div>
</section>
<section id="ejemplo-4.-pendiente-negativa" class="slide level2">
<h2>Ejemplo 4. Pendiente negativa</h2>
<p><code>bodyfat</code>: 252 hombres; densidad corporal (g/cm³) y circunferencia abdominal (cm).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a aria-hidden="true" tabindex="-1"></a>bodyfat <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"Bases/bodyfat.txt"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb80-2"><a aria-hidden="true" tabindex="-1"></a>bodyfat<span class="sc">$</span>Abdomen_10 <span class="ot">&lt;-</span> bodyfat<span class="sc">$</span>Abdomen <span class="sc">/</span> <span class="dv">10</span>     <span class="co"># unidades de 10 cm</span></span>
<span id="cb80-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a aria-hidden="true" tabindex="-1"></a>modelo_bf <span class="ot">&lt;-</span> <span class="fu">lm</span>(Density <span class="sc">~</span> Abdomen_10, <span class="at">data =</span> bodyfat)</span>
<span id="cb80-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">coef</span>(modelo_bf), <span class="fu">confint</span>(modelo_bf))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          2.5 %    97.5 %
(Intercept)  1.186087  1.173768  1.198407
Abdomen_10  -0.014101 -0.015423 -0.012779</code></pre>
</div>
</div>
<ul>
<li>Por cada <strong>10 cm</strong> más de circunferencia abdominal, la densidad corporal fue en promedio <strong>0.014 g/cm³ menor</strong> (IC 95 %: −0.0154 a −0.0128).</li>
<li>Signo negativo: más grasa abdominal → menor densidad (la grasa es menos densa que el músculo).</li>
</ul>
</section>
<section id="ejemplo-5.-pendiente-nula" class="slide level2">
<h2>Ejemplo 5. Pendiente “nula”</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a aria-hidden="true" tabindex="-1"></a>modelo_edad_ta <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Edad, <span class="at">data =</span> df)</span>
<span id="cb82-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">coef</span>(modelo_edad_ta), <span class="fu">confint</span>(modelo_edad_ta))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           2.5 %    97.5 %
(Intercept) 125.121815 117.91437 132.32926
Edad          0.016059  -0.11333   0.14545</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_edad_ta)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00078206</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\hat\beta_1 = 0.016\)</span> mmHg por año; IC 95 % −0.113 a 0.145 <strong>incluye 0</strong>; <span class="math inline">\(R^2 &lt; 0.001\)</span>.</li>
<li>Interpretación: <strong>no hay evidencia</strong> de asociación lineal entre edad y tensión en esta muestra.</li>
<li><strong>No</strong> es lo mismo que “la edad no afecta la tensión”: ausencia de evidencia ≠ evidencia de ausencia (¿potencia? ¿relación no lineal? ¿confusión?).</li>
</ul>
</section>
<section id="ejemplo-6.-predictor-binario-01" class="slide level2">
<h2>Ejemplo 6. Predictor binario (0/1)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Comorbilidades: 0 = no, 1 = sí</span></span>
<span id="cb86-2"><a aria-hidden="true" tabindex="-1"></a>modelo_com <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Comorbilidades, <span class="at">data =</span> df)</span>
<span id="cb86-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">coef</span>(modelo_com), <span class="fu">confint</span>(modelo_com))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            2.5 %   97.5 %
(Intercept)    123.8095 120.16249 127.4565
Comorbilidades   4.0007  -0.97378   8.9752</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(df<span class="sc">$</span>Tension_Arterial, df<span class="sc">$</span>Comorbilidades, mean)   <span class="co"># medias por grupo</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     0      1 
123.81 127.81 </code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\hat\beta_0 = 123.8\)</span> = media del grupo <strong>sin</strong> comorbilidades.</li>
<li><span class="math inline">\(\hat\beta_1 = 4.0\)</span> = <strong>diferencia de medias</strong> (con − sin). IC incluye 0; <em>p</em> = 0.11.</li>
<li>Es exactamente una <strong>prueba <em>t</em></strong> de dos muestras con varianzas iguales (<span class="math inline">\(t = 1.60\)</span>).</li>
</ul>
</section>
<section id="ejemplo-6b.-un-adelanto-de-la-parte-2" class="slide level2">
<h2>Ejemplo 6b. Un adelanto de la parte 2</h2>
<p>¿Qué pasa si agregamos el consumo de sal al modelo?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Comorbilidades ajustado por consumo de sal</span></span>
<span id="cb90-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Comorbilidades <span class="sc">+</span> Consumo_Sal, <span class="at">data =</span> df))[<span class="st">"Comorbilidades"</span>]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Comorbilidades 
        6.0527 </code></pre>
</div>
</div>
<div class="small">
<p>En el modelo completo del libro (sal + comorbilidades + tabaquismo + edad) el coeficiente es 5.91 mmHg <span class="citation" data-cites="perezguerrero2024bioestadistica">(<a href="#/referencias" role="doc-biblioref" onclick="">Pérez Guerrero 2024</a>)</span>.</p>
</div>
<div class="pregunta">
<p>El efecto de tener comorbilidades pasa de 4.0 mmHg (no significativo) a ≈ 6 mmHg al <strong>ajustar</strong> por el consumo de sal. ¿Por qué cambiaría un coeficiente al agregar otra variable? → <strong>Parte 2: ajuste por covariables y confusión.</strong></p>
</div>
</section>
<section id="ejemplo-7.-coeficientes-estandarizados" class="slide level2">
<h2>Ejemplo 7. Coeficientes estandarizados</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># scale() convierte a media 0 y desviación estándar 1</span></span>
<span id="cb92-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(<span class="fu">scale</span>(Tension_Arterial) <span class="sc">~</span> <span class="fu">scale</span>(Consumo_Sal), <span class="at">data =</span> df)) <span class="sc">|&gt;</span></span>
<span id="cb92-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept) scale(Consumo_Sal) 
             0.000              0.836 </code></pre>
</div>
</div>
<ul>
<li>Por cada <strong>1 DE</strong> más de consumo de sal (462 mg/24 h), la tensión es <strong>0.84 DE</strong> mayor.</li>
<li>En regresión simple, <span class="math inline">\(\hat\beta_{estandarizado} = r = 0.836\)</span>. ¡Volvimos al inicio!</li>
<li>Útil para comparar magnitudes entre predictores con distintas unidades; menos útil para comunicar resultados clínicos.</li>
</ul>
</section>
<section id="resumen-de-interpretación" class="slide level2">
<h2>Resumen de interpretación</h2>
<table class="caption-top">
<colgroup>
<col style="width: 29%">
<col style="width: 37%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Situación</th>
<th>Qué hacer con <span class="math inline">\(\hat\beta_1\)</span></th>
<th>Qué hacer con <span class="math inline">\(\hat\beta_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Unidad de <em>x</em> muy pequeña (mg)</td>
<td>Reescalar (g, 10 cm, 5 años)</td>
<td>—</td>
</tr>
<tr class="even">
<td><em>x</em> = 0 fuera del rango</td>
<td>—</td>
<td>Centrar <em>x</em> (media o valor de referencia)</td>
</tr>
<tr class="odd">
<td>Pendiente negativa</td>
<td>“<em>y</em> es en promedio … <strong>menor</strong>”</td>
<td>—</td>
</tr>
<tr class="even">
<td>IC incluye 0</td>
<td>“No hay evidencia de asociación”</td>
<td>—</td>
</tr>
<tr class="odd">
<td><em>x</em> binaria (0/1)</td>
<td>Diferencia de medias entre grupos</td>
<td>Media del grupo de referencia (0)</td>
</tr>
<tr class="even">
<td><em>x</em> estandarizada</td>
<td>Cambio en DE de <em>y</em> por 1 DE de <em>x</em> (= <em>r</em>)</td>
<td>0</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="cierre" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>Cierre</h1>

</section>
<section id="mensajes-clave" class="slide level2">
<h2>Mensajes clave</h2>
<ol type="1">
<li><strong>Correlación</strong> mide asociación simétrica sin unidades; <strong>regresión</strong> modela cuánto cambia <em>y</em> por <em>x</em>. Ninguna demuestra causalidad.</li>
<li>OLS elige la recta que <strong>minimiza</strong> <span class="math inline">\(\sum e_i^2\)</span>.</li>
<li>El <strong>ANOVA</strong> de la regresión particiona <span class="math inline">\(SST = SSR + SSE\)</span>; de ahí salen <span class="math inline">\(F\)</span>, <span class="math inline">\(R^2\)</span> y <span class="math inline">\(\hat\sigma\)</span>. <code>anova(m0, m1)</code> compara modelos anidados.</li>
<li><strong>Diagnostique</strong> siempre: <code>check_model()</code> + pruebas + criterio.</li>
<li>Interprete coeficientes <strong>en unidades con sentido clínico</strong>, con IC, y dentro del rango de los datos.</li>
</ol>
</section>
<section id="actividad-en-clase" class="slide level2">
<h2>Actividad en clase</h2>
<p>Con <code>LungCapData</code>:</p>
<ol type="1">
<li>Ajuste <code>LungCap ~ Height_cm</code> y <code>LungCap ~ Age</code>.</li>
<li>Para cada modelo: construya la tabla ANOVA <strong>a mano</strong> y compárela con <code>anova()</code>.</li>
<li>Diagnostique ambos modelos con <code>check_model()</code>. ¿Cumplen los supuestos? ¿Qué panel le preocupa más?</li>
<li>Reescale y/o centre el predictor para que <span class="math inline">\(\hat\beta_0\)</span> y <span class="math inline">\(\hat\beta_1\)</span> tengan interpretación clínica. Redacte los resultados como en un artículo.</li>
<li><strong>Para discutir:</strong> ¿cuál de los dos predictores elegiría si solo pudiera usar uno? Justifique con <span class="math inline">\(R^2\)</span>, <span class="math inline">\(\hat\sigma\)</span> y AIC (<code>compare_performance()</code>).</li>
</ol>
<div class="small">
<p>Próxima sesión: ¿qué pasa si metemos <strong>edad y estatura al mismo tiempo</strong>? → regresión múltiple, variables <em>dummy</em> y selección de variables.</p>
</div>
</section>
<section id="referencias" class="slide level2 smaller scrollable">
<h2>Referencias</h2>
<div id="refs" class="small references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-anscombe1973graphs" class="csl-entry" role="listitem">
Anscombe, F. J. 1973. <span>«Graphs in Statistical Analysis»</span>. <em>The American Statistician</em> 27 (1): 17-21. <a href="https://doi.org/10.1080/00031305.1973.10478966">https://doi.org/10.1080/00031305.1973.10478966</a>.
</div>
<div id="ref-denis2020univariate" class="csl-entry" role="listitem">
Denis, Daniel J. 2020. <em>Univariate, Bivariate, and Multivariate Statistics Using R: Quantitative Tools for Data Analysis and Data Science</em>. Hoboken, NJ: John Wiley &amp; Sons, Inc.
</div>
<div id="ref-fox2016applied" class="csl-entry" role="listitem">
Fox, John. 2016. <em>Applied Regression Analysis and Generalized Linear Models</em>. 3.ª ed. Thousand Oaks, CA: SAGE Publications.
</div>
<div id="ref-ludecke2021performance" class="csl-entry" role="listitem">
Lüdecke, Daniel, Mattan S. Ben-Shachar, Indrajeet Patil, Philip Waggoner, y Dominique Makowski. 2021. <span>«performance: An <span>R</span> Package for Assessment, Comparison and Testing of Statistical Models»</span>. <em>Journal of Open Source Software</em> 6 (60): 3139. <a href="https://doi.org/10.21105/joss.03139">https://doi.org/10.21105/joss.03139</a>.
</div>
<div id="ref-perezguerrero2024bioestadistica" class="csl-entry" role="listitem">
Pérez Guerrero, Edsaúl Emilio. 2024. <em>Bioestadística en R para ciencias de la salud: Guía práctica</em>. 1.ª ed. Zapopan, Jalisco, México: Editorial Innovación Educativa. <a href="https://www.cucs.udg.mx/libros/lectura_cucs.php?libro=Bioestadistica_enR_digital">https://www.cucs.udg.mx/libros/lectura_cucs.php?libro=Bioestadistica_enR_digital</a>.
</div>
<div id="ref-schmidt2018linear" class="csl-entry" role="listitem">
Schmidt, Amand F., y Chris Finan. 2018. <span>«Linear regression and the normality assumption»</span>. <em>Journal of Clinical Epidemiology</em> 98: 146-51. <a href="https://doi.org/10.1016/j.jclinepi.2017.12.006">https://doi.org/10.1016/j.jclinepi.2017.12.006</a>.
</div>
<div id="ref-schneider2010linear" class="csl-entry" role="listitem">
Schneider, Astrid, Gerhard Hommel, y Maria Blettner. 2010. <span>«Linear regression analysis: part 14 of a series on evaluation of scientific publications»</span>. <em>Deutsches Ärzteblatt International</em> 107 (44): 776-82. <a href="https://doi.org/10.3238/arztebl.2010.0776">https://doi.org/10.3238/arztebl.2010.0776</a>.
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Bioestadística Avanzada· Modelos lineales — Parte 1</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/Ed-Perez-G\.github\.io\/bioestadistica-avanzada\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>