project:
  type: website

website:
  title: "Bioestadística avanzada"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Acerca del curso
      - text: Temas
        menu:
          - href: temas/tema-01/index.qmd
            text: "Tema 1: Repaso de R y análisis reproducible"
            
  page-footer:
    left: "© 2026 Edsaúl E. Pérez-Guerrero"
    right: "Construido con [Quarto](https://quarto.org/); R version 4.5.1"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-title: "En esta página"
    code-copy: true

editor: visual