<!DOCTYPE html>
<html lang="es"><head>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Edsaúl Emilio Pérez-Guerrero">
  <meta name="dcterms.date" content="2026-09-27">
  <title>Bioestadística avanzada – Modelos lineales II</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
    /* CSS for citations */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
      margin-bottom: 0em;
    }
    .hanging-indent div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-992ed520baf37567c43dc1d740a96f26.css">
  <link rel="stylesheet" href="estilos.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Modelos lineales II</h1>
  <p class="subtitle">Regresión lineal múltiple · Variables <em>dummy</em> · ANOVA · Diagnóstico · Colinealidad · Confusión · Selección de variables</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Edsaúl Emilio Pérez-Guerrero 
</div>
</div>
</div>

  <p class="date">2026-09-27</p>
</section>
<section id="objetivos-de-la-sesión" class="slide level2">
<h2>Objetivos de la sesión</h2>
<p>Al terminar la sesión, usted podrá:</p>
<ol type="1">
<li>Justificar <strong>estadísticamente</strong> por qué un modelo necesita más de un predictor.</li>
<li>Incluir <strong>variables cualitativas</strong> mediante variables <em>dummy</em> e interpretar sus coeficientes.</li>
<li>Ajustar e <strong>interpretar</strong> un modelo de regresión lineal múltiple y su <strong>ANOVA</strong>.</li>
<li><strong>Diagnosticar</strong> el modelo, incluida la <strong>colinealidad</strong> (VIF).</li>
<li>Reconocer <strong>confusores</strong>, mediadores y colisionadores, y decidir cuándo ajustar.</li>
<li>Construir un modelo <strong>manualmente</strong> con criterios explícitos.</li>
</ol>
<aside class="notes">
<p>Tiempo total ≈ 120 min. ¿Por qué ajustar? (20) · Usos (5) · Dummy (15) · Modelo e interpretación (15) · ANOVA (10) · Diagnóstico (10) · Colinealidad (15) · ¿Por qué no todas? (5) · Confusores (10) · Selección manual (10) · Cierre (5).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="dónde-nos-quedamos" class="slide level2">
<h2>¿Dónde nos quedamos?</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Parte 1: regresión lineal simple</p>
<p><span class="math display">\[
\widehat{TA} = 74.84 + 0.0204 \cdot \text{Sal}
\]</span></p>
<ul>
<li><span class="math inline">\(R^2 = 0.699\)</span></li>
<li>Diagnóstico sin problemas</li>
</ul>
<p><strong>Pero</strong> la base tiene más variables:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Tipo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Sexo</code></td>
<td>Cualitativa (Hombre, Mujer)</td>
</tr>
<tr class="even">
<td><code>Comorbilidades</code></td>
<td>Cualitativa (0 = No, 1 = Sí)</td>
</tr>
<tr class="odd">
<td><code>Fuma</code></td>
<td>Cualitativa (0 = No fuma, 1 = Ex-fumador, 2 = Fumador)</td>
</tr>
<tr class="even">
<td><code>Edad</code></td>
<td>Cuantitativa (años)</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:45%;">
<div class="pregunta">
<p>¿El 0.0204 mmHg por mg de sal es el efecto <strong>de la sal</strong>… o también de otras cosas que acompañan a la sal?</p>
</div>
</div></div>
</section>
<section id="preparar-la-base-como-en-el-libro" class="slide level2">
<h2>Preparar la base (como en el libro)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Bases/sal_tension_arterial.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir los códigos numéricos en factores con etiquetas</span></span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Comorbilidades <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Comorbilidades, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Si"</span>))</span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Fuma <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Fuma, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No fuma"</span>, <span class="st">"Ex-fumador"</span>, <span class="st">"Fumador"</span>))</span>
<span id="cb1-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   80 obs. of  6 variables:
 $ Consumo_Sal     : num  1345 1517 1657 1726 1867 ...
 $ Tension_Arterial: num  106 115 110 102 112 ...
 $ Sexo            : Factor w/ 2 levels "Hombre","Mujer": 2 2 2 2 2 1 2 2 2 1 ...
 $ Comorbilidades  : Factor w/ 2 levels "No","Si": 1 2 2 1 2 1 2 2 2 2 ...
 $ Fuma            : Factor w/ 3 levels "No fuma","Ex-fumador",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Edad            : int  72 23 59 71 79 18 34 32 20 19 ...</code></pre>
</div>
</div>
<div class="alerta">
<p>En regresión es <strong>indispensable</strong> que las variables cualitativas sean <code>factor</code> y que sus niveles estén en el orden correcto: el <strong>primer nivel</strong> será la categoría de referencia.</p>
</div>
</section>
<section>
<section id="por-qué-ajustar-por-otras-variables" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>1. ¿Por qué ajustar por otras variables?</h1>

</section>
<section id="la-tensión-arterial-cambia-según-otras-variables" class="slide level2">
<h2>La tensión arterial cambia según otras variables</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Fuma, <span class="at">y =</span> Tension_Arterial, <span class="at">fill =</span> Fuma)) <span class="sc">+</span></span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> colores_fuma) <span class="sc">+</span></span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"TA sistólica (mmHg)"</span>)</span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Comorbilidades, <span class="at">y =</span> Tension_Arterial)) <span class="sc">+</span></span>
<span id="cb3-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"#dbe8f5"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="cn">NULL</span>)</span>
<span id="cb3-6"><a aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Sexo, <span class="at">y =</span> Tension_Arterial)) <span class="sc">+</span></span>
<span id="cb3-7"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"#dbe8f5"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="cn">NULL</span>)</span>
<span id="cb3-8"><a aria-hidden="true" tabindex="-1"></a>g1 <span class="sc">+</span> g2 <span class="sc">+</span> g3 <span class="sc">+</span> <span class="fu">plot_layout</span>(<span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>))   <span class="co"># patchwork une las gráficas</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Modelos_lineales_P2_files/figure-revealjs/fig-boxplots-ta-1.png" id="fig-boxplots-ta" width="1200" class="r-stretch quarto-figure-center"><p class="caption">
Figura&nbsp;1
</p></section>
<section id="pruebas-de-hipótesis-qué-se-asocia-con-la-ta" class="slide level2">
<h2>Pruebas de hipótesis: ¿qué se asocia con la TA?</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(Tension_Arterial <span class="sc">~</span> Fuma, <span class="at">data =</span> df))           <span class="co"># ANOVA de una vía</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value              Pr(&gt;F)    
Fuma         2   6251    3126    64.2 &lt;0.0000000000000002 ***
Residuals   77   3752      49                                
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Tension_Arterial <span class="sc">~</span> Comorbilidades, <span class="at">data =</span> df)<span class="sc">$</span>p.value</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.11746</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Tension_Arterial <span class="sc">~</span> Sexo, <span class="at">data =</span> df)<span class="sc">$</span>p.value</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.74554</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="sc">~</span> Tension_Arterial <span class="sc">+</span> Edad, <span class="at">data =</span> df)<span class="sc">$</span>p.value</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8055</code></pre>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Asociación con la TA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fuma</td>
<td><strong>Fuerte</strong> (F = 64.1, <em>p</em> &lt; 0.001)</td>
</tr>
<tr class="even">
<td>Comorbilidades</td>
<td>Débil, no significativa (<em>p</em> = 0.11)</td>
</tr>
<tr class="odd">
<td>Sexo</td>
<td>No (<em>p</em> = 0.75)</td>
</tr>
<tr class="even">
<td>Edad</td>
<td>No (<em>p</em> = 0.81)</td>
</tr>
</tbody>
</table>
</section>
<section id="la-pregunta-clave-se-asocian-también-con-la-sal" class="slide level2">
<h2>La pregunta clave: ¿se asocian también con la <strong>sal</strong>?</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Fuma, <span class="at">y =</span> Consumo_Sal, <span class="at">fill =</span> Fuma)) <span class="sc">+</span></span>
<span id="cb12-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> colores_fuma) <span class="sc">+</span></span>
<span id="cb12-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Consumo de sal (mg/24h)"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Modelos_lineales_P2_files/figure-revealjs/fig-sal-fuma-1.png" id="fig-sal-fuma" width="1200" class="r-stretch quarto-figure-center"><p class="caption">
Figura&nbsp;2
</p><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(Consumo_Sal <span class="sc">~</span> Fuma, <span class="at">data =</span> df))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df   Sum Sq Mean Sq F value              Pr(&gt;F)    
Fuma         2 11947211 5973606    93.8 &lt;0.0000000000000002 ***
Residuals   77  4904394   63693                                
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="los-fumadores-consumen-más-sal-y-tienen-mayor-ta" class="slide level2">
<h2>Los fumadores consumen más sal <strong>y</strong> tienen mayor TA</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> Consumo_Sal, <span class="at">y =</span> Tension_Arterial, <span class="at">col =</span> Fuma)) <span class="sc">+</span></span>
<span id="cb15-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> colores_fuma) <span class="sc">+</span></span>
<span id="cb15-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Consumo de sal (mg/24h)"</span>, <span class="at">y =</span> <span class="st">"Tensión arterial sistólica (mmHg)"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="Modelos_lineales_P2_files/figure-revealjs/fig-scatter-fuma-1.png" id="fig-scatter-fuma" width="1200" class="r-stretch quarto-figure-center"><p class="caption">
Figura&nbsp;3
</p><div class="pregunta">
<p>Si ignoramos el tabaquismo, ¿a quién le “atribuimos” la TA alta de los fumadores?</p>
</div>
</section>
<section id="resumen-estadístico-quién-podría-distorsionar-el-efecto-de-la-sal" class="slide level2">
<h2>Resumen estadístico: ¿quién podría distorsionar el efecto de la sal?</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>¿Asociada con la <strong>TA</strong>?</th>
<th>¿Asociada con la <strong>sal</strong>?</th>
<th>Implicación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Fuma</strong></td>
<td>Sí (<em>p</em> &lt; 0.001)</td>
<td>Sí (<em>p</em> &lt; 0.001)</td>
<td>Posible <strong>confusor</strong></td>
</tr>
<tr class="even">
<td><strong>Comorbilidades</strong></td>
<td><em>p</em> = 0.11</td>
<td>No (<em>p</em> = 0.35)</td>
<td>Puede <strong>mejorar la precisión</strong></td>
</tr>
<tr class="odd">
<td>Sexo</td>
<td>No (<em>p</em> = 0.75)</td>
<td>No (<em>p</em> = 0.96)</td>
<td>Poco aporte estadístico</td>
</tr>
<tr class="even">
<td>Edad</td>
<td>No (<em>p</em> = 0.81)</td>
<td>No (<em>p</em> = 0.80)</td>
<td>Poco aporte estadístico</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Consumo_Sal <span class="sc">~</span> Comorbilidades, <span class="at">data =</span> df)   <span class="co"># p = 0.35</span></span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Consumo_Sal <span class="sc">~</span> Sexo, <span class="at">data =</span> df)             <span class="co"># p = 0.96</span></span>
<span id="cb16-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Edad, <span class="at">data =</span> df)         <span class="co"># p = 0.80</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="small">
<p>La <strong>plausibilidad biológica</strong> decide qué variables <em>deben</em> considerarse; las pruebas solo describen lo que ocurre en esta muestra.</p>
</div>
</section>
<section id="el-efecto-de-la-sal-cambia-al-ajustar" class="slide level2">
<h2>El efecto de la sal cambia al ajustar</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a>crudo    <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal, <span class="at">data =</span> df)</span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a>ajustado <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Fuma, <span class="at">data =</span> df)</span>
<span id="cb17-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(crudo)[<span class="st">"Consumo_Sal"</span>]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Consumo_Sal 
    0.02037 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(ajustado)[<span class="st">"Consumo_Sal"</span>]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Consumo_Sal 
   0.014292 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Cambio porcentual del coeficiente de la sal</span></span>
<span id="cb21-2"><a aria-hidden="true" tabindex="-1"></a>(<span class="fu">coef</span>(crudo)[<span class="st">"Consumo_Sal"</span>] <span class="sc">-</span> <span class="fu">coef</span>(ajustado)[<span class="st">"Consumo_Sal"</span>]) <span class="sc">/</span></span>
<span id="cb21-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(crudo)[<span class="st">"Consumo_Sal"</span>] <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Consumo_Sal 
     29.838 </code></pre>
</div>
</div>
<div class="clave">
<p>Al ajustar por tabaquismo, el coeficiente de la sal <strong>baja 30 %</strong> (0.0204 → 0.0143). Parte de lo que atribuíamos a la sal era en realidad del tabaquismo.</p>
</div>
</section>
<section id="visualmente-pendiente-cruda-vs.-ajustada" class="slide level2">
<h2>Visualmente: pendiente cruda vs.&nbsp;ajustada</h2>

<img data-src="Modelos_lineales_P2_files/figure-revealjs/fig-crudo-ajustado-1.png" id="fig-crudo-ajustado" width="1200" class="r-stretch quarto-figure-center"><p class="caption">
Figura&nbsp;4
</p><div class="small">
<p>El modelo ajustado estima <strong>una pendiente común</strong> dentro de cada grupo de tabaquismo. Si las pendientes pudieran ser distintas por grupo → <strong>interacción</strong> (parte 3).</p>
</div>
</section>
<section id="y-las-comorbilidades-se-descubren-al-ajustar" class="slide level2">
<h2>Y las comorbilidades se “descubren” al ajustar</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Comorbilidades, <span class="at">data =</span> df))[<span class="st">"ComorbilidadesSi"</span>]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ComorbilidadesSi 
          4.0007 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Comorbilidades <span class="sc">+</span> Consumo_Sal, <span class="at">data =</span> df))[<span class="st">"ComorbilidadesSi"</span>]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ComorbilidadesSi 
          6.0527 </code></pre>
</div>
</div>
<ul>
<li>Sin ajustar: 4.0 mmHg, <em>p</em> = 0.11. Ajustando por sal: 6.1 mmHg, <em>p</em> &lt; 0.001.</li>
<li>¿Por qué? (1) Los pacientes con comorbilidades consumían <strong>un poco menos</strong> de sal (2 465 vs.&nbsp;2 562 mg), lo que <strong>enmascaraba</strong> su efecto; (2) al explicar la variabilidad debida a la sal, el <strong>error residual se reduce</strong> y la estimación se vuelve más precisa.</li>
</ul>
<div class="clave">
<p>Ajustar no solo <strong>corrige sesgos</strong>; también puede <strong>aumentar la precisión</strong> y revelar asociaciones ocultas.</p>
</div>
</section></section>
<section>
<section id="para-qué-sirve-la-regresión-múltiple" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>2. ¿Para qué sirve la regresión múltiple?</h1>

</section>
<section id="el-modelo" class="slide level2">
<h2>El modelo</h2>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \cdots + \beta_k x_{ki} + \varepsilon_i, \qquad \varepsilon_i \sim N(0, \sigma^2)
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_1, \dots, \beta_k\)</span> son <strong>coeficientes de regresión parcial</strong>: el cambio esperado en <em>y</em> por una unidad de <span class="math inline">\(x_j\)</span> <strong>manteniendo constantes</strong> los demás predictores <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span>.</li>
<li>Se estima igual que antes: <span class="math inline">\(\hat{\boldsymbol\beta} = (X^TX)^{-1}X^T\mathbf{y}\)</span>, ahora con más columnas en <span class="math inline">\(X\)</span>.</li>
<li>Geométricamente ya no es una recta: con 2 predictores numéricos es un <strong>plano</strong>; con más, un <strong>hiperplano</strong>.</li>
</ul>
</section>
<section id="usos-de-la-regresión-múltiple" class="slide level2">
<h2>Usos de la regresión múltiple</h2>
<table class="caption-top">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Objetivo</th>
<th>Pregunta</th>
<th>Ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Aislar el efecto</strong> de una variable</td>
<td>¿Cuál es el efecto de <em>x</em> <strong>independientemente</strong> de <em>z</em>?</td>
<td>Efecto de la sal independiente del tabaquismo</td>
</tr>
<tr class="even">
<td><strong>Ajustar</strong> por confusores</td>
<td>¿El efecto crudo está sesgado?</td>
<td>Sal ajustada por tabaquismo</td>
</tr>
<tr class="odd">
<td><strong>Efecto conjunto</strong> de varias variables</td>
<td>¿Cuánto explican <strong>en conjunto</strong>?</td>
<td><span class="math inline">\(R^2\)</span> de sal + comorbilidades + tabaquismo</td>
</tr>
<tr class="even">
<td><strong>Predecir</strong></td>
<td>¿Qué TA espero en un paciente con estas características?</td>
<td>Modelo pronóstico</td>
</tr>
<tr class="odd">
<td><strong>Mejorar la precisión</strong></td>
<td>¿Puedo reducir el error residual?</td>
<td>Comorbilidades</td>
</tr>
<tr class="even">
<td>Evaluar <strong>modificación del efecto</strong></td>
<td>¿El efecto de <em>x</em> cambia según <em>z</em>?</td>
<td>Interacciones (parte 3)</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="variables-cualitativas-y-variables-dummy" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>3. Variables cualitativas y variables <em>dummy</em></h1>

</section>
<section id="cómo-entra-una-variable-cualitativa-a-una-ecuación" class="slide level2">
<h2>¿Cómo entra una variable cualitativa a una ecuación?</h2>
<ul>
<li><strong>Dicotómica</strong> (Comorbilidades): se codifica 0 = No, 1 = Sí. Su <span class="math inline">\(\beta\)</span> es la <strong>diferencia de medias</strong> entre grupos (ajustada).</li>
<li><strong>Tres o más niveles</strong> (Fuma: No fuma, Ex-fumador, Fumador): ¿a quién le toca 0, 1 o 2?</li>
</ul>
<div class="alerta">
<p>Nunca meta <code>Fuma</code> como número 0/1/2. Eso obliga a que el efecto de pasar de “No fuma” a “Ex-fumador” sea <strong>idéntico</strong> al de pasar de “Ex-fumador” a “Fumador” (supuesto de linealidad entre categorías).</p>
</div>
<p><strong>Solución</strong>: crear <span class="math inline">\(k - 1\)</span> variables <em>dummy</em> (indicadoras) para una variable con <span class="math inline">\(k\)</span> niveles <span class="citation" data-cites="perezguerrero2024bioestadistica">(<a href="#/referencias" role="doc-biblioref" onclick="">Pérez Guerrero 2024</a>)</span>.</p>
</section>
<section id="variables-dummy-el-ejemplo-del-tabaquismo" class="slide level2">
<h2>Variables <em>dummy</em>: el ejemplo del tabaquismo</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Categoría</th>
<th style="text-align: center;"><span class="math inline">\(x_1\)</span> (Ex-fumador)</th>
<th style="text-align: center;"><span class="math inline">\(x_2\)</span> (Fumador)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>No fumador</strong> (referencia)</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td>Ex-fumador</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td>Fumador</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<ul>
<li>3 niveles → <strong>2</strong> variables <em>dummy</em>.</li>
<li>La categoría con todos ceros es la <strong>referencia</strong> (estado basal): cada <em>dummy</em> compara su nivel <strong>contra</strong> ella.</li>
<li>Las <em>dummy</em> solo tienen sentido <strong>en conjunto</strong>; nunca se analizan por separado ni fuera del modelo.</li>
</ul>
</section>
<section id="r-crea-las-dummy" class="slide level2">
<h2><code>R</code> crea las <em>dummy</em></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(df<span class="sc">$</span>Fuma)   <span class="co"># así codifica R el factor Fuma</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Ex-fumador Fumador
No fuma             0       0
Ex-fumador          1       0
Fumador             0       1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Matriz de diseño X que usa lm() (primeras 6 filas)</span></span>
<span id="cb29-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(<span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Comorbilidades <span class="sc">+</span> Fuma <span class="sc">+</span> Edad, <span class="at">data =</span> df))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) Consumo_Sal ComorbilidadesSi FumaEx-fumador FumaFumador Edad
1           1      1345.4                0              0           0   72
2           1      1516.7                1              0           0   23
3           1      1656.7                1              0           0   59
4           1      1725.6                0              0           0   71
5           1      1867.3                1              0           0   79
6           1      1867.5                0              0           0   18</code></pre>
</div>
</div>
<div class="small">
<p>Por eso en la salida aparecen <code>ComorbilidadesSi</code>, <code>FumaEx-fumador</code> y <code>FumaFumador</code>: el nombre de la variable + el nivel comparado contra la referencia.</p>
</div>
</section>
<section id="dummy-para-la-variable-tabaquismo" class="slide level2">
<h2><em>Dummy</em> para la variable tabaquismo</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-hidden="true" tabindex="-1"></a>modelo_fuma <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Fuma, <span class="at">data =</span> df)</span>
<span id="cb31-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(modelo_fuma)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) FumaEx-fumador    FumaFumador 
      115.4744         7.2406        20.0363 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(df<span class="sc">$</span>Tension_Arterial, df<span class="sc">$</span>Fuma, mean)   <span class="co"># medias por grupo</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   No fuma Ex-fumador    Fumador 
    115.47     122.71     135.51 </code></pre>
</div>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Coeficiente</th>
<th>Valor</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat\beta_0\)</span></td>
<td>115.5</td>
<td>Media de TA de los <strong>no fumadores</strong> (referencia)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\hat\beta_{Ex}\)</span></td>
<td>7.2</td>
<td>Ex-fumadores − no fumadores = 122.7 − 115.5</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\hat\beta_{Fum}\)</span></td>
<td>20.0</td>
<td>Fumadores − no fumadores = 135.5 − 115.5</td>
</tr>
</tbody>
</table>
</section>
<section id="cambiar-la-categoría-de-referencia" class="slide level2">
<h2>Cambiar la categoría de referencia</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df</span>
<span id="cb35-2"><a aria-hidden="true" tabindex="-1"></a>df2<span class="sc">$</span>Fuma <span class="ot">&lt;-</span> <span class="fu">relevel</span>(df2<span class="sc">$</span>Fuma, <span class="at">ref =</span> <span class="st">"Fumador"</span>)   <span class="co"># ahora la referencia es "Fumador"</span></span>
<span id="cb35-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Comorbilidades <span class="sc">+</span> Fuma <span class="sc">+</span> Edad, <span class="at">data =</span> df2))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept)      Consumo_Sal ComorbilidadesSi      FumaNo fuma 
       86.838458         0.015340         5.910124        -7.105188 
  FumaEx-fumador             Edad 
       -4.389837         0.015292 </code></pre>
</div>
</div>
<ul>
<li>El modelo es <strong>el mismo</strong> (<span class="math inline">\(R^2\)</span>, residuales, predicciones idénticos); solo cambia <strong>qué comparación</strong> se reporta.</li>
<li>Elija la referencia por las <strong>razones correctas</strong> (grupo sin exposición, grupo más grande, grupo control).</li>
</ul>
</section></section>
<section>
<section id="el-modelo-de-para-el-consumo-de-sal-ajustado" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>4. El modelo de para el consumo de sal ajustado</h1>

</section>
<section id="ajustar-el-modelo" class="slide level2">
<h2>Ajustar el modelo</h2>
<p>Cada variable se agrega con <code>+</code> y en el caso de interacciones con <code>*</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Comorbilidades <span class="sc">+</span> Fuma <span class="sc">+</span> Edad,</span>
<span id="cb37-2"><a aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> df)</span>
<span id="cb37-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Tension_Arterial ~ Consumo_Sal + Comorbilidades + 
    Fuma + Edad, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-12.387  -3.113  -0.741   3.223  12.627 

Coefficients:
                 Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)      79.73327    5.39774   14.77 &lt; 0.0000000000000002 ***
Consumo_Sal       0.01534    0.00239    6.42          0.000000012 ***
ComorbilidadesSi  5.91012    1.19555    4.94          0.000004647 ***
FumaEx-fumador    2.71535    1.80301    1.51               0.1363    
FumaFumador       7.10519    2.50541    2.84               0.0059 ** 
Edad              0.01529    0.03051    0.50               0.6177    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.27 on 74 degrees of freedom
Multiple R-squared:  0.795, Adjusted R-squared:  0.781 
F-statistic: 57.3 on 5 and 74 DF,  p-value: &lt;0.0000000000000002</code></pre>
</div>
</div>
</section>
<section id="intervalos-de-confianza" class="slide level2">
<h2>Intervalos de confianza</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modelo) <span class="sc">|&gt;</span> <span class="fu">round</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %  97.5 %
(Intercept)      68.9780 90.4885
Consumo_Sal       0.0106  0.0201
ComorbilidadesSi  3.5279  8.2923
FumaEx-fumador   -0.8772  6.3079
FumaFumador       2.1131 12.0973
Edad             -0.0455  0.0761</code></pre>
</div>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Término</th>
<th><span class="math inline">\(\hat\beta\)</span></th>
<th>EE</th>
<th>IC 95 %</th>
<th><em>p</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercepto</td>
<td>79.733</td>
<td>5.398</td>
<td>68.978 a 90.489</td>
<td>&lt; 0.001</td>
</tr>
<tr class="even">
<td>Consumo de sal</td>
<td>0.0153</td>
<td>0.0024</td>
<td>0.0106 a 0.0201</td>
<td>&lt; 0.001</td>
</tr>
<tr class="odd">
<td>Comorbilidades (Sí)</td>
<td>5.910</td>
<td>1.196</td>
<td>3.528 a 8.292</td>
<td>&lt; 0.001</td>
</tr>
<tr class="even">
<td>Ex-fumador</td>
<td>2.715</td>
<td>1.803</td>
<td>−0.877 a 6.308</td>
<td>0.136</td>
</tr>
<tr class="odd">
<td>Fumador</td>
<td>7.105</td>
<td>2.505</td>
<td>2.113 a 12.097</td>
<td>0.006</td>
</tr>
<tr class="even">
<td>Edad</td>
<td>0.0153</td>
<td>0.0305</td>
<td>−0.046 a 0.076</td>
<td>0.618</td>
</tr>
</tbody>
</table>
</section>
<section id="interpretación-de-los-coeficientes-1" class="slide level2">
<h2>Interpretación de los coeficientes (1)</h2>
<ol type="1">
<li><p><strong>Intercepto (79.73; IC 95 % 68.98 a 90.49)</strong>: TA esperada cuando <strong>todas</strong> las variables valen cero (sal = 0 mg, sin comorbilidades, no fumador, 0 años). Necesario para la ecuación, <strong>sin interpretación clínica</strong>.</p></li>
<li><p><strong>Consumo de sal (0.0153; IC 95 % 0.0106 a 0.0201; <em>p</em> &lt; 0.001)</strong>: por cada 1 mg/24 h adicional de sal, la TA aumenta en promedio <strong>0.015 mmHg</strong> (≈ <strong>15.3 mmHg por gramo</strong>), <strong>manteniendo constantes</strong> comorbilidades, tabaquismo y edad.</p></li>
<li><p><strong>Comorbilidades (5.91; IC 95 % 3.53 a 8.29; <em>p</em> &lt; 0.001)</strong>: tener comorbilidades se asocia con una TA en promedio <strong>5.9 mmHg mayor</strong> que no tenerlas, manteniendo constantes las demás variables.</p></li>
</ol>
</section>
<section id="interpretación-de-los-coeficientes-2" class="slide level2">
<h2>Interpretación de los coeficientes (2)</h2>
<ol start="4" type="1">
<li><p><strong>Ex-fumador (2.72; IC 95 % −0.88 a 6.31; <em>p</em> = 0.136)</strong>: comparado con <strong>no fumadores</strong>, ser ex-fumador no tuvo un efecto estadísticamente significativo; el IC <strong>incluye 0</strong>.</p></li>
<li><p><strong>Fumador (7.11; IC 95 % 2.11 a 12.10; <em>p</em> = 0.006)</strong>: comparado con <strong>no fumadores</strong>, ser fumador se asocia con una TA en promedio <strong>7.1 mmHg mayor</strong>, manteniendo constantes las demás variables.</p></li>
<li><p><strong>Edad (0.015; IC 95 % −0.046 a 0.076; <em>p</em> = 0.618)</strong>: no hay evidencia de asociación entre la edad y la TA en este modelo.</p></li>
</ol>
<div class="clave">
<p><strong>Conclusión</strong>: sal, comorbilidades y ser fumador se asocian de forma independiente con la TA. El modelo explica ≈ <strong>79.5 %</strong> de la variabilidad (<span class="math inline">\(R^2 = 0.795\)</span>; <span class="math inline">\(R^2_{aj} = 0.781\)</span>).</p>
</div>
</section>
<section id="crudo-vs.-ajustado-la-tabla-que-se-reporta" class="slide level2">
<h2>Crudo vs.&nbsp;ajustado: la tabla que se reporta</h2>
<table class="caption-top">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th><span class="math inline">\(\hat\beta\)</span> crudo (modelo simple)</th>
<th><span class="math inline">\(\hat\beta\)</span> ajustado (modelo múltiple)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sal (por g/24 h)</td>
<td>20.4 (17.4 a 23.4)</td>
<td>15.3 (10.6 a 20.1)</td>
</tr>
<tr class="even">
<td>Comorbilidades (Sí)</td>
<td>4.0 (−1.0 a 9.0)</td>
<td>5.9 (3.5 a 8.3)</td>
</tr>
<tr class="odd">
<td>Ex-fumador</td>
<td>7.2 (3.0 a 11.4)</td>
<td>2.7 (−0.9 a 6.3)</td>
</tr>
<tr class="even">
<td>Fumador</td>
<td>20.0 (16.4 a 23.6)</td>
<td>7.1 (2.1 a 12.1)</td>
</tr>
<tr class="odd">
<td>Edad (por año)</td>
<td>0.02 (−0.11 a 0.15)</td>
<td>0.02 (−0.05 a 0.08)</td>
</tr>
</tbody>
</table>
<div class="small">
<p>El efecto crudo del tabaquismo (20 mmHg) se reduce a 7.1 mmHg: buena parte se explicaba por el mayor consumo de sal de los fumadores. La confusión es <strong>recíproca</strong>.</p>
</div>
</section>
<section id="r2-ajustado" class="slide level2">
<h2><span class="math inline">\(R^2\)</span> ajustado</h2>
<p><span class="math display">\[
R^2_{aj} = 1 - \frac{(1 - R^2)(n - 1)}{n - p - 1}
\]</span></p>
<ul>
<li><span class="math inline">\(R^2\)</span> <strong>nunca disminuye</strong> al agregar variables, aunque sean ruido.</li>
<li><span class="math inline">\(R^2_{aj}\)</span> <strong>penaliza</strong> cada predictor adicional: solo sube si la variable aporta más de lo que “cuesta”.</li>
<li>Úselo (o AIC/BIC) para <strong>comparar</strong> modelos con distinto número de predictores <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.79487</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)<span class="sc">$</span>adj.r.squared</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.78101</code></pre>
</div>
</div>
</section></section>
<section>
<section id="anova-del-modelo-múltiple" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>5. ANOVA del modelo múltiple</h1>

</section>
<section id="f-global-el-modelo-sirve-para-algo" class="slide level2">
<h2><em>F</em> global: ¿el modelo sirve para algo?</h2>
<p><code>F-statistic: 57.35 on 5 and 74 DF, p-value: &lt; 2.2e-16</code></p>
<ul>
<li><span class="math inline">\(H_0: \beta_1 = \beta_2 = \cdots = \beta_5 = 0\)</span> (ningún predictor explica la TA).</li>
<li>gl del numerador = <strong>5</strong> = número de coeficientes sin contar el intercepto (Fuma aporta 2).</li>
<li>gl del denominador = <span class="math inline">\(n - p - 1 = 80 - 5 - 1 = 74\)</span>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a aria-hidden="true" tabindex="-1"></a>modelo_nulo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> df)</span>
<span id="cb45-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_nulo, modelo)   <span class="co"># mismo F global</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Tension_Arterial ~ 1
Model 2: Tension_Arterial ~ Consumo_Sal + Comorbilidades + Fuma + Edad
  Res.Df   RSS Df Sum of Sq    F              Pr(&gt;F)    
1     79 10003                                          
2     74  2052  5      7951 57.4 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="anova-sumas-de-cuadrados-secuenciales-tipo-i" class="slide level2">
<h2><code>anova()</code>: sumas de cuadrados <strong>secuenciales</strong> (tipo I)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Tension_Arterial
               Df Sum Sq Mean Sq F value               Pr(&gt;F)    
Consumo_Sal     1   6992    6992  252.16 &lt; 0.0000000000000002 ***
Comorbilidades  1    720     720   25.98            0.0000026 ***
Fuma            2    231     116    4.17                0.019 *  
Edad            1      7       7    0.25                0.618    
Residuals      74   2052      28                                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>Cada fila prueba la variable <strong>dado lo que entró antes</strong>: la sal entra sola (SC = 6 992), las comorbilidades se evalúan después de la sal, etc.</li>
<li>La suma de todas las SC + residual = SST (10 003).</li>
</ul>
</section>
<section id="el-orden-importa" class="slide level2">
<h2>¡El orden importa!</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a aria-hidden="true" tabindex="-1"></a>modelo_orden2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Edad <span class="sc">+</span> Fuma <span class="sc">+</span> Comorbilidades <span class="sc">+</span> Consumo_Sal,</span>
<span id="cb49-2"><a aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> df)</span>
<span id="cb49-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(modelo_orden2)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Tension_Arterial
               Df Sum Sq Mean Sq F value               Pr(&gt;F)    
Edad            1      8       8    0.28                  0.6    
Fuma            2   6249    3125  112.68 &lt; 0.0000000000000002 ***
Comorbilidades  1    552     552   19.91          0.000028495 ***
Consumo_Sal     1   1142    1142   41.19          0.000000012 ***
Residuals      74   2052      28                                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="alerta">
<p>Fuma pasa de SC = 231 a SC = 6 249 solo por entrar <strong>antes</strong> que la sal. Los coeficientes de <code>summary()</code> son idénticos en ambos órdenes; lo que cambia es la <strong>pregunta</strong> que responde cada fila de <code>anova()</code>.</p>
</div>
</section>
<section id="sc-tipo-ii-cada-variable-ajustada-por-las-demás" class="slide level2">
<h2>SC tipo II: cada variable ajustada por las demás</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(modelo, <span class="at">type =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type II tests)

Response: Tension_Arterial
               Sum Sq Df F value      Pr(&gt;F)    
Consumo_Sal      1142  1   41.19 0.000000012 ***
Comorbilidades    678  1   24.44 0.000004647 ***
Fuma              226  2    4.08       0.021 *  
Edad                7  1    0.25       0.618    
Residuals        2052 74                        
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>Cada fila: ¿cuánto aporta la variable <strong>después de todas las demás</strong>? No depende del orden.</li>
<li>Para variables numéricas o dicotómicas, <em>F</em> tipo II = <span class="math inline">\(t^2\)</span> de <code>summary()</code> (sal: <span class="math inline">\(6.418^2 = 41.19\)</span>).</li>
<li><strong>Fuma</strong> se prueba <strong>como un todo</strong> (2 gl): <em>F</em> = 4.08, <em>p</em> = 0.021. ¿El tabaquismo aporta algo? Sí.</li>
</ul>
<div class="small">
<p>Las pruebas <em>t</em> de cada <em>dummy</em> comparan un nivel contra la referencia; la prueba <em>F</em> con 2 gl responde si la <strong>variable completa</strong> importa.</p>
</div>
</section>
<section id="comparar-modelos-anidados" class="slide level2">
<h2>Comparar modelos anidados</h2>
<p>¿Las covariables, <strong>en conjunto</strong>, mejoran el modelo de solo sal?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(crudo, modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Tension_Arterial ~ Consumo_Sal
Model 2: Tension_Arterial ~ Consumo_Sal + Comorbilidades + Fuma + Edad
  Res.Df  RSS Df Sum of Sq    F    Pr(&gt;F)    
1     78 3011                                
2     74 2052  4       959 8.65 0.0000088 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><span class="math display">\[
F = \frac{(SSE_{reducido} - SSE_{completo}) / (gl_{reducido} - gl_{completo})}{SSE_{completo} / gl_{completo}} = \frac{(3010.8 - 2052.0)/4}{2052.0/74} = 8.65
\]</span></p>
<div class="clave">
<p>Esta prueba será la <strong>herramienta central</strong> para construir modelos manualmente (sección 9).</p>
</div>
</section></section>
<section>
<section id="diagnóstico" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>6. Diagnóstico</h1>

</section>
<section id="los-mismos-supuestos-y-uno-más" class="slide level2">
<h2>Los mismos supuestos… y uno más</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Supuesto</th>
<th>Herramienta en <code>performance</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Linealidad</td>
<td><code>check_model()</code> (panel <em>Linearity</em>)</td>
</tr>
<tr class="even">
<td>Independencia</td>
<td><code>check_autocorrelation()</code> y el diseño del estudio</td>
</tr>
<tr class="odd">
<td>Normalidad de residuales</td>
<td><code>check_normality()</code></td>
</tr>
<tr class="even">
<td>Homocedasticidad</td>
<td><code>check_heteroscedasticity()</code></td>
</tr>
<tr class="odd">
<td>Observaciones influyentes</td>
<td><code>check_outliers()</code></td>
</tr>
<tr class="even">
<td><strong>Ausencia de colinealidad</strong></td>
<td><code>check_collinearity()</code> (<strong>nuevo</strong>)</td>
</tr>
</tbody>
</table>
</section>
<section id="check_model-del-modelo-múltiple" class="slide level2">
<h2><code>check_model()</code> del modelo múltiple</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="check_model-del-modelo-múltiple-output" class="slide level2 output-location-slide"><h2><code>check_model()</code> del modelo múltiple</h2><div class="cell output-location-slide">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="Modelos_lineales_P2_files/figure-revealjs/check-model-1.png" width="1500"></p>
</figure>
</div>
</div>
</div></section><section id="pruebas-individuales" class="slide level2">
<h2>Pruebas individuales</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.518).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.697).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_outliers</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: No outliers detected.
- Based on the following method and threshold: cook (0.8).
- For variable: (Whole model)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">model_performance</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Indices of model performance

AIC   |  AICc |   BIC |    R2 | R2 (adj.) |  RMSE | Sigma
---------------------------------------------------------
500.6 | 502.1 | 517.3 | 0.795 |     0.781 | 5.065 | 5.266</code></pre>
</div>
</div>
<div class="small">
<p>Los supuestos se cumplen razonablemente. En regresión múltiple aparece un panel nuevo en <code>check_model()</code>: <strong>colinealidad</strong>.</p>
</div>
</section></section>
<section>
<section id="colinealidad" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>7. Colinealidad</h1>

</section>
<section id="qué-es-la-colinealidad" class="slide level2">
<h2>¿Qué es la colinealidad?</h2>
<ul>
<li>Dos o más <strong>predictores</strong> están altamente correlacionados entre sí (multicolinealidad si son varios).</li>
<li>Recordemos: <span class="math inline">\(\hat\beta_j\)</span> es el efecto de <span class="math inline">\(x_j\)</span> <strong>manteniendo constantes</strong> los demás. Si <span class="math inline">\(x_1\)</span> y <span class="math inline">\(x_2\)</span> se mueven casi siempre juntos, ¿cómo “mantener constante” uno mientras cambia el otro?</li>
<li>El modelo <strong>no puede separar</strong> sus efectos → estimaciones <strong>inestables</strong>.</li>
</ul>
<p><strong>Consecuencias</strong>:</p>
<ul>
<li>Errores estándar <strong>inflados</strong> → IC anchos, <em>p</em> grandes.</li>
<li>Coeficientes que <strong>cambian bruscamente</strong> (incluso de <strong>signo</strong>) al agregar o quitar una variable.</li>
<li>El <span class="math inline">\(R^2\)</span> y las predicciones <strong>no</strong> se afectan; el problema es la <strong>interpretación</strong> de cada <span class="math inline">\(\hat\beta\)</span>.</li>
</ul>
</section>
<section id="caso-extremo-colinealidad-perfecta-denis2020univariate" class="slide level2">
<h2>Caso extremo: colinealidad perfecta <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>)</span>
<span id="cb64-2"><a aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">20</span>)   <span class="co"># p2 = 2 * p1: combinación lineal exacta</span></span>
<span id="cb64-3"><a aria-hidden="true" tabindex="-1"></a>y  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">15</span>, <span class="dv">8</span>, <span class="dv">4</span>, <span class="dv">1</span>)</span>
<span id="cb64-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> p1 <span class="sc">+</span> p2))       <span class="co"># R elimina p2: NA</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          p1          p2 
      17.90       -1.65          NA </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">12</span>, <span class="dv">16</span>, <span class="dv">21</span>)   <span class="co"># cambiamos un solo valor</span></span>
<span id="cb66-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> p1 <span class="sc">+</span> p2))<span class="sc">$</span>coefficients, <span class="dv">3</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)    17.50      3.940   4.441    0.047
p1              0.45     10.694   0.042    0.970
p2             -1.00      5.087  -0.197    0.862</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(<span class="fu">lm</span>(y <span class="sc">~</span> p1 <span class="sc">+</span> p2))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> p1  p2 
442 442 </code></pre>
</div>
</div>
<div class="small">
<p>Con solo <code>p1</code>: <span class="math inline">\(\hat\beta = -1.65\)</span> (<em>p</em> = 0.03). Con <code>p1</code> y <code>p2</code>: <span class="math inline">\(\hat\beta_{p1} = 0.45\)</span>, EE = 10.7 → cambió de signo y perdió toda precisión.</p>
</div>
</section>
<section id="ejemplo-con-nuestros-datos-sal-y-sodio-urinario" class="slide level2">
<h2>Ejemplo con nuestros datos: sal y sodio urinario</h2>
<p>Supongamos que además medimos el <strong>sodio urinario de 24 h</strong>, un biomarcador casi idéntico al consumo de sal (lo simulamos):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2024</span>)</span>
<span id="cb70-2"><a aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Sodio_orina <span class="ot">&lt;-</span> df<span class="sc">$</span>Consumo_Sal <span class="sc">*</span> <span class="fl">0.39</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">80</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">15</span>)</span>
<span id="cb70-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(df<span class="sc">$</span>Consumo_Sal, df<span class="sc">$</span>Sodio_orina)   <span class="co"># correlación casi perfecta</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.99637</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a aria-hidden="true" tabindex="-1"></a>modelo_colineal <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Sodio_orina <span class="sc">+</span></span>
<span id="cb72-2"><a aria-hidden="true" tabindex="-1"></a>                        Comorbilidades <span class="sc">+</span> Fuma <span class="sc">+</span> Edad, <span class="at">data =</span> df)</span>
<span id="cb72-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(modelo_colineal)<span class="sc">$</span>coefficients[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, ], <span class="dv">4</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  78.8237     5.3571 14.7140   0.0000
Consumo_Sal  -0.0100     0.0151 -0.6601   0.5113
Sodio_orina   0.0656     0.0386  1.6988   0.0936</code></pre>
</div>
</div>
</section>
<section id="qué-pasó-con-la-sal" class="slide level2">
<h2>¿Qué pasó con la sal?</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Modelo del sal</th>
<th>+ Sodio urinario</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\hat\beta\)</span> sal</td>
<td><strong>0.0153</strong></td>
<td><strong>−0.0100</strong> (¡signo negativo!)</td>
</tr>
<tr class="even">
<td>EE sal</td>
<td>0.0024</td>
<td>0.0151 (6 veces mayor)</td>
</tr>
<tr class="odd">
<td><em>p</em> sal</td>
<td>&lt; 0.001</td>
<td>0.51</td>
</tr>
<tr class="even">
<td><span class="math inline">\(R^2\)</span></td>
<td>0.795</td>
<td>0.803</td>
</tr>
</tbody>
</table>
<div class="alerta">
<p>Conclusión absurda: “la sal <strong>disminuye</strong> la TA y no es significativa”. El modelo predice igual de bien (<span class="math inline">\(R^2\)</span> similar), pero los coeficientes individuales <strong>ya no son interpretables</strong>.</p>
</div>
<div class="small">
<p>La solución aquí es sustantiva: sal y sodio urinario miden <strong>el mismo constructo</strong>; incluya solo uno.</p>
</div>
</section>
<section id="factor-de-inflación-de-la-varianza-vif" class="slide level2">
<h2>Factor de inflación de la varianza (VIF)</h2>
<p><span class="math display">\[
VIF_j = \frac{1}{1 - R_j^2}
\]</span></p>
<ul>
<li><span class="math inline">\(R_j^2\)</span>: el <span class="math inline">\(R^2\)</span> de una regresión de <span class="math inline">\(x_j\)</span> <strong>sobre los demás predictores</strong>. ¿Qué tanto de <span class="math inline">\(x_j\)</span> ya está explicado por los otros?</li>
<li><span class="math inline">\(\sqrt{VIF_j}\)</span> = cuántas veces se <strong>infla el error estándar</strong> de <span class="math inline">\(\hat\beta_j\)</span> respecto a predictores no correlacionados.</li>
<li><strong>Tolerancia</strong> <span class="math inline">\(= 1/VIF = 1 - R_j^2\)</span>.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>VIF</th>
<th>Interpretación orientativa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Sin correlación con los demás predictores</td>
</tr>
<tr class="even">
<td>1 – 5</td>
<td>Baja a moderada</td>
</tr>
<tr class="odd">
<td>5 – 10</td>
<td>Alta: revisar</td>
</tr>
<tr class="even">
<td>&gt; 10</td>
<td>Muy alta: problema serio</td>
</tr>
</tbody>
</table>
<div class="small">
<p>Los puntos de corte son <strong>orientativos</strong>, no reglas rígidas <span class="citation" data-cites="obrien2007caution">(<a href="#/referencias" role="doc-biblioref" onclick="">O’Brien 2007</a>)</span>. Con factores de más de 2 niveles se usa el <strong>GVIF</strong> <span class="citation" data-cites="fox1992generalized">(<a href="#/referencias" role="doc-biblioref" onclick="">Fox y Monette 1992</a>)</span>.</p>
</div>
</section>
<section id="vif-en-r" class="slide level2">
<h2>VIF en R</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_collinearity</span>(modelo)            <span class="co"># modelo del libro</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for Multicollinearity

Low Correlation

           Term  VIF      VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
    Consumo_Sal 3.47 [2.54,    4.96]     1.86      0.29     [0.20, 0.39]
 Comorbilidades 1.03 [1.00,   93.18]     1.01      0.98     [0.01, 1.00]
           Fuma 3.51 [2.57,    5.02]     1.37      0.28     [0.20, 0.39]
           Edad 1.02 [1.00, 1249.46]     1.01      0.98     [0.00, 1.00]</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">check_collinearity</span>(modelo_colineal)   <span class="co"># con sodio urinario</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for Multicollinearity

Low Correlation

           Term  VIF      VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
 Comorbilidades 1.03 [ 1.00,  72.73]     1.01      0.97     [0.01, 1.00]
           Fuma 3.57 [ 2.62,   5.09]     1.37      0.28     [0.20, 0.38]
           Edad 1.04 [ 1.00,   7.58]     1.02      0.96     [0.13, 1.00]

High Correlation

        Term    VIF      VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
 Consumo_Sal 141.60 [96.32, 208.38]    11.90  7.06e-03     [0.00, 0.01]
 Sodio_orina 143.68 [97.74, 211.45]    11.99  6.96e-03     [0.00, 0.01]</code></pre>
</div>
</div>
<div class="small">
<p>En el modelo del libro sal y Fuma tienen VIF ≈ 3.5 (se relacionan: los fumadores consumen más sal), aceptable. Con el sodio urinario, VIF &gt; 140.</p>
</div>
</section>
<section id="vif-a-mano" class="slide level2">
<h2>VIF “a mano”</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># R^2 de la sal explicada por los demás predictores del modelo del libro</span></span>
<span id="cb78-2"><a aria-hidden="true" tabindex="-1"></a>r2_sal <span class="ot">&lt;-</span> <span class="fu">summary</span>(<span class="fu">lm</span>(Consumo_Sal <span class="sc">~</span> Comorbilidades <span class="sc">+</span> Fuma <span class="sc">+</span> Edad, <span class="at">data =</span> df))<span class="sc">$</span>r.squared</span>
<span id="cb78-3"><a aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> r2_sal)   <span class="co"># VIF de la sal</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.4722</code></pre>
</div>
</div>
<p><strong>¿Qué hacer ante colinealidad alta?</strong></p>
<ul>
<li>Preguntarse si ambas variables miden <strong>lo mismo</strong> → quedarse con una.</li>
<li>Combinarlas en un índice o puntaje (p.&nbsp;ej., componentes principales).</li>
<li>Centrar variables cuando la colinealidad viene de términos polinomiales o interacciones (parte 3).</li>
<li>No eliminar automáticamente variables con VIF moderado si son confusores necesarios.</li>
</ul>
</section></section>
<section>
<section id="por-qué-no-incluir-todas-las-variables" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>8. ¿Por qué no incluir todas las variables?</h1>

</section>
<section id="más-variables-mejor-modelo" class="slide level2">
<h2>Más variables ≠ mejor modelo</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a aria-hidden="true" tabindex="-1"></a>modelo_todas <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Comorbilidades <span class="sc">+</span> Fuma <span class="sc">+</span> Edad <span class="sc">+</span> Sexo,</span>
<span id="cb80-2"><a aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> df)</span>
<span id="cb80-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(crudo, modelo, modelo_todas)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name         | Model | AIC (weights) | AICc (weights) | BIC (weights) |    R2
-----------------------------------------------------------------------------
crudo        |    lm | 523.3 (&lt;.001) |  523.6 (&lt;.001) | 530.4 (0.001) | 0.699
modelo       |    lm | 500.6 (0.714) |  502.1 (0.760) | 517.3 (0.890) | 0.795
modelo_todas |    lm | 502.4 (0.286) |  504.4 (0.240) | 521.5 (0.108) | 0.795

Name         | R2 (adj.) |  RMSE | Sigma
----------------------------------------
crudo        |     0.695 | 6.135 | 6.213
modelo       |     0.781 | 5.065 | 5.266
modelo_todas |     0.778 | 5.059 | 5.296</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(R^2\)</span> sube (0.7953 vs.&nbsp;0.7949), pero <span class="math inline">\(R^2_{aj}\)</span> <strong>baja</strong> y AIC <strong>sube</strong>: Sexo solo agrega ruido.</li>
</ul>
</section>
<section id="razones-para-no-meter-todo" class="slide level2">
<h2>Razones para no meter todo</h2>
<ol type="1">
<li><strong>Sobreajuste</strong>: el modelo aprende el ruido de <em>esta</em> muestra y predice mal en otra. Regla orientativa: ≈ 10–15 observaciones por coeficiente estimado <span class="citation" data-cites="harrell2015regression">(<a href="#/referencias" role="doc-biblioref" onclick="">Harrell 2015</a>)</span>. Con <em>n</em> = 80, ≈ 5–8 coeficientes.</li>
<li><strong>Pérdida de precisión</strong>: cada coeficiente cuesta 1 gl; variables irrelevantes inflan los EE.</li>
<li><strong>Colinealidad</strong>: más variables → más probabilidad de predictores redundantes.</li>
<li><strong>Sesgo por sobreajuste causal</strong>: ajustar por <strong>mediadores</strong> o <strong>colisionadores</strong> <em>introduce</em> sesgo <span class="citation" data-cites="schisterman2009overadjustment">(<a href="#/referencias" role="doc-biblioref" onclick="">Schisterman, Cole, y Platt 2009</a>)</span>.</li>
<li><strong>Interpretabilidad</strong> y <strong>parsimonia</strong>: entre dos modelos que explican lo mismo, el más simple es preferible (navaja de Occam) <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span>.</li>
<li><strong>Comparaciones múltiples</strong>: con muchas variables, algunas saldrán “significativas” por azar.</li>
</ol>
</section></section>
<section>
<section id="variables-confusoras" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>9. Variables confusoras</h1>

</section>
<section id="qué-es-un-confusor" class="slide level2">
<h2>¿Qué es un confusor?</h2>
<p>Una variable <em>Z</em> que distorsiona la asociación entre la exposición <em>X</em> y el desenlace <em>Y</em> porque:</p>
<ol type="1">
<li>Se asocia con la <strong>exposición</strong> (<em>X</em>).</li>
<li>Se asocia con el <strong>desenlace</strong> (<em>Y</em>) independientemente de <em>X</em>.</li>
<li><strong>No</strong> está en la vía causal entre <em>X</em> y <em>Y</em> (no es consecuencia de <em>X</em>).</li>
</ol>

<img data-src="Modelos_lineales_P2_files/figure-revealjs/dag-confusor-1.png" width="1200" class="r-stretch"><div class="small">
<p><strong>Ajustar</strong> por un confusor elimina (parcialmente) el sesgo. Recuerde el helado y los tiburones: la <strong>temperatura</strong> es el confusor.</p>
</div>
</section>
<section id="confusor-mediador-y-colisionador" class="slide level2">
<h2>Confusor, mediador y colisionador</h2>

<img data-src="Modelos_lineales_P2_files/figure-revealjs/dag-tres-1.png" width="1800" class="r-stretch"><table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Confusor</th>
<th>Mediador</th>
<th>Colisionador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estructura</td>
<td>X ← Z → Y</td>
<td>X → M → Y</td>
<td>X → C ← Y</td>
</tr>
<tr class="even">
<td>¿Ajustar?</td>
<td><strong>Sí</strong></td>
<td><strong>No</strong>, si busca el efecto total</td>
<td><strong>Nunca</strong></td>
</tr>
<tr class="odd">
<td>Si ajusta…</td>
<td>Elimina sesgo</td>
<td>Elimina parte del efecto real</td>
<td><strong>Crea</strong> una asociación falsa</td>
</tr>
</tbody>
</table>
</section>
<section id="simulación-ajustar-por-un-mediador-o-un-colisionador" class="slide level2">
<h2>Simulación: ajustar por un mediador o un colisionador</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>); n <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb82-2"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Mediador: X -&gt; M -&gt; Y (efecto total de X sobre Y = 0.8 * 0.5 = 0.4)</span></span>
<span id="cb82-3"><a aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n); m <span class="ot">&lt;-</span> <span class="fl">0.8</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(n); y <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">*</span> m <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb82-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x))[<span class="st">"x"</span>]        <span class="co"># efecto total ≈ 0.35</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      x 
0.35007 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> m))[<span class="st">"x"</span>]    <span class="co"># ¡el efecto "desaparece"!</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       x 
0.028222 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb86-2"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Colisionador: X -&gt; C &lt;- Y (X y Y NO están relacionadas)</span></span>
<span id="cb86-3"><a aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n); y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n); c <span class="ot">&lt;-</span> x <span class="sc">+</span> y <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb86-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x))[<span class="st">"x"</span>]        <span class="co"># ≈ 0: sin asociación</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        x 
-0.036324 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> c))[<span class="st">"x"</span>]    <span class="co"># ≈ -0.55: ¡asociación falsa!</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       x 
-0.54737 </code></pre>
</div>
</div>
</section>
<section id="cuándo-incluir-una-variable-y-cuándo-no" class="slide level2">
<h2>¿Cuándo incluir una variable y cuándo no?</h2>
<p><strong>Incluir</strong> <span class="citation" data-cites="vanderweele2019principles">(<a href="#/referencias" role="doc-biblioref" onclick="">VanderWeele 2019</a>)</span>:</p>
<ul>
<li>Confusores conocidos o plausibles (causas de la exposición, del desenlace o de ambas).</li>
<li>Variables fuertemente asociadas al desenlace aunque no a la exposición → <strong>mejoran la precisión</strong> (comorbilidades).</li>
<li>Variables de diseño (estratificación, centro, lote).</li>
</ul>
<p><strong>No incluir</strong>:</p>
<ul>
<li><strong>Mediadores</strong> (si interesa el efecto total).</li>
<li><strong>Colisionadores</strong> y consecuencias del desenlace.</li>
<li>Variables que miden lo mismo que la exposición (sodio urinario).</li>
<li>Variables solo asociadas con la exposición (no mejoran nada y aumentan la varianza).</li>
</ul>
<div class="clave">
<p>La decisión de ajustar es <strong>causal y sustantiva</strong> (diagramas causales, DAG) antes que estadística <span class="citation" data-cites="greenland1999causal">(<a href="#/referencias" role="doc-biblioref" onclick="">Greenland, Pearl, y Robins 1999</a>)</span>.</p>
</div>
</section>
<section id="criterio-estadístico-complementario-cambio-en-el-estimador" class="slide level2">
<h2>Criterio estadístico complementario: cambio en el estimador</h2>
<p>Una variable se considera confusora <strong>en los datos</strong> si su inclusión cambia el coeficiente de la exposición en ≥ 10 % <span class="citation" data-cites="mickey1989impact">(<a href="#/referencias" role="doc-biblioref" onclick="">Mickey y Greenland 1989</a>)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a aria-hidden="true" tabindex="-1"></a>b_crudo <span class="ot">&lt;-</span> <span class="fu">coef</span>(crudo)[<span class="st">"Consumo_Sal"</span>]</span>
<span id="cb90-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-3"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Cambio (%) del coeficiente de la sal al agregar cada variable por separado</span></span>
<span id="cb90-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">c</span>(<span class="st">"Fuma"</span>, <span class="st">"Comorbilidades"</span>, <span class="st">"Edad"</span>, <span class="st">"Sexo"</span>), <span class="cf">function</span>(v) {</span>
<span id="cb90-5"><a aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"Tension_Arterial ~ Consumo_Sal +"</span>, v)), <span class="at">data =</span> df)</span>
<span id="cb90-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>((<span class="fu">coef</span>(m)[[<span class="st">"Consumo_Sal"</span>]] <span class="sc">-</span> b_crudo) <span class="sc">/</span> b_crudo <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb90-7"><a aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Fuma.Consumo_Sal Comorbilidades.Consumo_Sal 
                     -29.8                        3.4 
          Edad.Consumo_Sal           Sexo.Consumo_Sal 
                       0.2                        0.0 </code></pre>
</div>
</div>
<div class="small">
<p>Solo el tabaquismo cumple el criterio (−29.8 %). Úselo como <strong>apoyo</strong>, nunca para “descubrir” confusores sin justificación teórica: un mediador o colisionador también cambia el estimador.</p>
</div>
</section></section>
<section>
<section id="cómo-seleccionar-variables" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>10. ¿Cómo seleccionar variables?</h1>

</section>
<section id="opciones-disponibles" class="slide level2">
<h2>Opciones disponibles</h2>
<table class="caption-top">
<colgroup>
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Estrategia</th>
<th>Quién decide</th>
<th>Idea</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Por conocimiento</strong> (simultánea)</td>
<td>Investigador</td>
<td>Todas las variables justificadas entran a la vez <span class="citation" data-cites="denis2020univariate">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>)</span></td>
</tr>
<tr class="even">
<td><strong>Jerárquica</strong> (por bloques)</td>
<td>Investigador</td>
<td>Se agregan bloques en un orden teórico y se evalúa el <span class="math inline">\(\Delta R^2\)</span></td>
</tr>
<tr class="odd">
<td><strong>Manual / intencionada</strong> (<em>purposeful</em>)</td>
<td>Investigador + criterios estadísticos</td>
<td>Tamizaje, modelo completo, eliminación paso a paso con control de confusión <span class="citation" data-cites="bursac2008purposeful">(<a href="#/referencias" role="doc-biblioref" onclick="">Bursac et&nbsp;al. 2008</a>)</span></td>
</tr>
<tr class="even">
<td><strong>Automática</strong> (<em>forward</em>, <em>backward</em>, <em>stepwise</em>, mejor subconjunto)</td>
<td>Algoritmo</td>
<td>Maximizar un criterio (<em>p</em>, AIC) — <strong>próxima sesión</strong></td>
</tr>
<tr class="odd">
<td><strong>Penalizada</strong> (LASSO, <em>ridge</em>)</td>
<td>Algoritmo</td>
<td>Encoge coeficientes; útil para predicción con muchas variables</td>
</tr>
</tbody>
</table>
<div class="small">
<p>Ninguna estrategia es universalmente correcta. Para <strong>explicar</strong>, domina el conocimiento previo; para <strong>predecir</strong>, la validación <span class="citation" data-cites="heinze2018variable">(<a href="#/referencias" role="doc-biblioref" onclick="">Heinze, Wallisch, y Dunkler 2018</a>)</span>.</p>
</div>
</section>
<section id="estrategia-jerárquica-por-bloques" class="slide level2">
<h2>Estrategia jerárquica (por bloques)</h2>
<p>El investigador decide <strong>el orden</strong>: primero la exposición, luego variables clínicas, luego estilo de vida.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a aria-hidden="true" tabindex="-1"></a>bloque1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal, <span class="at">data =</span> df)</span>
<span id="cb92-2"><a aria-hidden="true" tabindex="-1"></a>bloque2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Comorbilidades, <span class="at">data =</span> df)</span>
<span id="cb92-3"><a aria-hidden="true" tabindex="-1"></a>bloque3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Comorbilidades <span class="sc">+</span> Fuma, <span class="at">data =</span> df)</span>
<span id="cb92-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(bloque1, bloque2, bloque3)   <span class="co"># ¿cada bloque mejora al anterior?</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Tension_Arterial ~ Consumo_Sal
Model 2: Tension_Arterial ~ Consumo_Sal + Comorbilidades
Model 3: Tension_Arterial ~ Consumo_Sal + Comorbilidades + Fuma
  Res.Df  RSS Df Sum of Sq     F    Pr(&gt;F)    
1     78 3011                                 
2     77 2290  1       720 26.24 0.0000023 ***
3     75 2059  2       231  4.22     0.018 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">summary</span>(bloque1)<span class="sc">$</span>r.squared, <span class="fu">summary</span>(bloque2)<span class="sc">$</span>r.squared, <span class="fu">summary</span>(bloque3)<span class="sc">$</span>r.squared)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.69901 0.77103 0.79417</code></pre>
</div>
</div>
<div class="small">
<p>Comorbilidades agrega <span class="math inline">\(\Delta R^2 = 0.072\)</span>; el tabaquismo, <span class="math inline">\(\Delta R^2 = 0.023\)</span> adicional. Ambos bloques mejoran significativamente el modelo.</p>
</div>
</section>
<section id="selección-manual-el-procedimiento" class="slide level2">
<h2>Selección manual: el procedimiento</h2>
<ol type="1">
<li><strong>Análisis bivariado</strong> de cada candidata con el desenlace. Pasan las que tienen <em>p</em> &lt; 0.20–0.25 <strong>o</strong> relevancia clínica (umbral laxo para no perder confusores) <span class="citation" data-cites="bursac2008purposeful">(<a href="#/referencias" role="doc-biblioref" onclick="">Bursac et&nbsp;al. 2008</a>)</span>.</li>
<li><strong>Modelo multivariable</strong> con todas las que pasaron.</li>
<li><strong>Eliminar una a una</strong> las no significativas (la de mayor <em>p</em> primero), comprobando:
<ul>
<li>que el modelo reducido no sea peor (<code>anova()</code> de modelos anidados, AIC, <span class="math inline">\(R^2_{aj}\)</span>);</li>
<li>que los coeficientes de las variables que quedan <strong>no cambien &gt; 10–20 %</strong> (si cambian, la variable es confusora y <strong>se queda</strong>).</li>
</ul></li>
<li><strong>Reintroducir</strong> una a una las variables excluidas en el paso 1 para ver si aportan ajustadas.</li>
<li><strong>Diagnosticar</strong> el modelo final (supuestos, VIF, influyentes) y valorar interacciones (parte 3).</li>
</ol>
<div class="alerta">
<p>Las variables que su <strong>marco teórico</strong> exige (confusores conocidos) se <strong>fuerzan</strong> en el modelo aunque no sean significativas.</p>
</div>
</section>
<section id="paso-1.-tamizaje-bivariado" class="slide level2">
<h2>Paso 1. Tamizaje bivariado</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a aria-hidden="true" tabindex="-1"></a>candidatas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Consumo_Sal"</span>, <span class="st">"Comorbilidades"</span>, <span class="st">"Fuma"</span>, <span class="st">"Edad"</span>, <span class="st">"Sexo"</span>)</span>
<span id="cb96-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-3"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Valor p de la F de cada modelo simple TA ~ variable</span></span>
<span id="cb96-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(candidatas, <span class="cf">function</span>(v) {</span>
<span id="cb96-5"><a aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"Tension_Arterial ~"</span>, v)), <span class="at">data =</span> df)</span>
<span id="cb96-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="fu">anova</span>(m)<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>], <span class="dv">4</span>)</span>
<span id="cb96-7"><a aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Consumo_Sal Comorbilidades           Fuma           Edad           Sexo 
        0.0000         0.1134         0.0000         0.8055         0.7464 </code></pre>
</div>
</div>
<ul>
<li>Pasan (<em>p</em> &lt; 0.25): <strong>Consumo_Sal, Comorbilidades, Fuma</strong>.</li>
<li>No pasan: Edad (0.81) y Sexo (0.75). Si su marco teórico los exige (la edad es un factor de riesgo reconocido de hipertensión), <strong>se fuerzan</strong>. Aquí los evaluaremos para ilustrar.</li>
</ul>
</section>
<section id="pasos-2-y-3.-modelo-completo-y-eliminación" class="slide level2">
<h2>Pasos 2 y 3. Modelo completo y eliminación</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a aria-hidden="true" tabindex="-1"></a>completo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Tension_Arterial <span class="sc">~</span> Consumo_Sal <span class="sc">+</span> Comorbilidades <span class="sc">+</span> Fuma <span class="sc">+</span> Edad <span class="sc">+</span> Sexo,</span>
<span id="cb98-2"><a aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> df)</span>
<span id="cb98-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(completo, <span class="at">test =</span> <span class="st">"F"</span>)   <span class="co"># F de quitar cada variable (tipo II)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
Tension_Arterial ~ Consumo_Sal + Comorbilidades + Fuma + Edad + 
    Sexo
               Df Sum of Sq  RSS AIC F value      Pr(&gt;F)    
&lt;none&gt;                      2048 273                        
Consumo_Sal     1      1126 3174 306   40.16 0.000000017 ***
Comorbilidades  1       670 2717 294   23.88 0.000005889 ***
Fuma            2       229 2277 278    4.09       0.021 *  
Edad            1         6 2054 272    0.21       0.647    
Sexo            1         4 2052 272    0.16       0.694    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Se elimina primero <strong>Sexo</strong> (mayor <em>p</em>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a aria-hidden="true" tabindex="-1"></a>sin_sexo <span class="ot">&lt;-</span> <span class="fu">update</span>(completo, . <span class="sc">~</span> . <span class="sc">-</span> Sexo)   <span class="co"># quitar Sexo</span></span>
<span id="cb100-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(sin_sexo, completo)                     <span class="co"># ¿empeora? No (p = 0.69)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Tension_Arterial ~ Consumo_Sal + Comorbilidades + Fuma + Edad
Model 2: Tension_Arterial ~ Consumo_Sal + Comorbilidades + Fuma + Edad + 
    Sexo
  Res.Df  RSS Df Sum of Sq    F Pr(&gt;F)
1     74 2052                         
2     73 2048  1      4.38 0.16   0.69</code></pre>
</div>
</div>
</section>
<section id="paso-3-cont..-control-del-cambio-en-los-coeficientes" class="slide level2">
<h2>Paso 3 (cont.). Control del cambio en los coeficientes</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a aria-hidden="true" tabindex="-1"></a>sin_edad <span class="ot">&lt;-</span> <span class="fu">update</span>(sin_sexo, . <span class="sc">~</span> . <span class="sc">-</span> Edad)    <span class="co"># ahora quitar Edad</span></span>
<span id="cb102-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(sin_edad, sin_sexo)                     <span class="co"># ¿empeora? No (p = 0.62)</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: Tension_Arterial ~ Consumo_Sal + Comorbilidades + Fuma
Model 2: Tension_Arterial ~ Consumo_Sal + Comorbilidades + Fuma + Edad
  Res.Df  RSS Df Sum of Sq    F Pr(&gt;F)
1     75 2059                         
2     74 2052  1      6.97 0.25   0.62</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># ¿Cambió el coeficiente de la sal al quitar variables?</span></span>
<span id="cb104-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">completo =</span> <span class="fu">coef</span>(completo)[<span class="st">"Consumo_Sal"</span>],</span>
<span id="cb104-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">sin_sexo =</span> <span class="fu">coef</span>(sin_sexo)[<span class="st">"Consumo_Sal"</span>],</span>
<span id="cb104-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">sin_edad =</span> <span class="fu">coef</span>(sin_edad)[<span class="st">"Consumo_Sal"</span>])</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>completo.Consumo_Sal sin_sexo.Consumo_Sal sin_edad.Consumo_Sal 
            0.015273             0.015340             0.015267 </code></pre>
</div>
</div>
<div class="small">
<p>El coeficiente de la sal cambia &lt; 1 %: Sexo y Edad <strong>no confunden</strong> y no aportan. Tampoco cambian los de Comorbilidades y Fuma (compruébelo con <code>coef()</code>).</p>
</div>
</section>
<section id="pasos-4-y-5.-modelo-final" class="slide level2">
<h2>Pasos 4 y 5. Modelo final</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a aria-hidden="true" tabindex="-1"></a>modelo_final <span class="ot">&lt;-</span> sin_edad</span>
<span id="cb106-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">summary</span>(modelo_final)<span class="sc">$</span>coefficients, <span class="dv">4</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)       80.6303     5.0669 15.9130   0.0000
Consumo_Sal        0.0153     0.0024  6.4313   0.0000
ComorbilidadesSi   5.9534     1.1865  5.0178   0.0000
FumaEx-fumador     2.8178     1.7824  1.5809   0.1181
FumaFumador        7.1905     2.4871  2.8911   0.0050</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(modelo, modelo_final)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name         | Model | AIC (weights) | AICc (weights) | BIC (weights) |    R2
-----------------------------------------------------------------------------
modelo       |    lm | 500.6 (0.296) |  502.1 (0.256) | 517.3 (0.114) | 0.795
modelo_final |    lm | 498.9 (0.704) |  500.0 (0.744) | 513.2 (0.886) | 0.794

Name         | R2 (adj.) |  RMSE | Sigma
----------------------------------------
modelo       |     0.781 | 5.065 | 5.266
modelo_final |     0.783 | 5.073 | 5.240</code></pre>
</div>
</div>
<ul>
<li>Modelo final: <strong>TA ~ Sal + Comorbilidades + Fuma</strong> (<span class="math inline">\(R^2_{aj} = 0.783\)</span>, menor AIC).</li>
<li>Paso 5: <code>check_model(modelo_final)</code> y <code>check_collinearity(modelo_final)</code> antes de reportar.</li>
<li>¿Y la edad? Si es un confusor teórico, reporte el modelo <strong>con</strong> edad: los resultados son prácticamente iguales, y eso también es un hallazgo.</li>
</ul>
</section>
<section id="estrategias-manuales-ventajas-y-cuidados" class="slide level2">
<h2>Estrategias manuales: ventajas y cuidados</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Ventajas</th>
<th>Cuidados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>El investigador controla cada decisión</td>
<td>Requiere documentar <strong>todos</strong> los pasos</td>
</tr>
<tr class="even">
<td>Integra conocimiento y criterios estadísticos</td>
<td>Los valores <em>p</em> del modelo final son optimistas (el modelo se eligió con los mismos datos)</td>
</tr>
<tr class="odd">
<td>Protege a los confusores (criterio de cambio)</td>
<td>Umbrales (0.25, 10 %) arbitrarios; justifíquelos</td>
</tr>
<tr class="even">
<td>Transparente y reproducible</td>
<td>Con muchas candidatas se vuelve impráctico → algoritmos</td>
</tr>
</tbody>
</table>
<div class="clave">
<p>Próxima sesión: <strong>algoritmos de selección</strong> (<em>forward</em>, <em>backward</em>, <em>stepwise</em>, mejor subconjunto) con <code>step()</code> / <code>MASS::stepAIC()</code>, y por qué son controvertidos <span class="citation" data-cites="denis2020univariate heinze2018variable">(<a href="#/referencias" role="doc-biblioref" onclick="">Denis 2020</a>; <a href="#/referencias" role="doc-biblioref" onclick="">Heinze, Wallisch, y Dunkler 2018</a>)</span>.</p>
</div>
</section></section>
<section>
<section id="cierre" class="title-slide slide level1 center" data-background-color="#1f4e79">
<h1>Cierre</h1>

</section>
<section id="mensajes-clave" class="slide level2">
<h2>Mensajes clave</h2>
<ol type="1">
<li>El efecto crudo puede estar <strong>distorsionado</strong>: el tabaquismo explicaba 30 % del efecto aparente de la sal.</li>
<li>Los coeficientes múltiples son <strong>parciales</strong>: “manteniendo constantes las demás variables”.</li>
<li>Variables cualitativas → <span class="math inline">\(k - 1\)</span> <em>dummy</em>; cada una se compara con la <strong>referencia</strong>; la variable completa se prueba con <em>F</em>.</li>
<li><code>anova()</code> es <strong>secuencial</strong> (el orden importa); <code>car::Anova()</code> tipo II no; <code>anova(m1, m2)</code> compara modelos anidados.</li>
<li>La <strong>colinealidad</strong> no afecta la predicción pero destruye la interpretación; revise el VIF.</li>
<li>Ajuste por <strong>confusores</strong>, no por mediadores ni colisionadores; más variables no es mejor.</li>
<li>Seleccione variables con <strong>teoría primero</strong> y criterios estadísticos explícitos después.</li>
</ol>
</section>
<section id="actividad-en-clase" class="slide level2">
<h2>Actividad en clase</h2>
<p>Pregunta: <strong>¿el consumo de sal se asocia con la TA independientemente de las demás variables?</strong></p>
<ol type="1">
<li>Ajuste al menos <strong>tres modelos alternativos</strong> para la misma pregunta: (a) crudo, (b) ajustado solo por confusores que usted justifique, (c) modelo del libro.</li>
<li>Para cada uno: coeficiente de la sal (por <strong>gramo</strong>/24 h) con IC 95 %, <span class="math inline">\(R^2_{aj}\)</span> y AIC (<code>compare_performance()</code>).</li>
<li>Justifique <strong>por escrito</strong> cada covariable: ¿confusor, variable de precisión o ninguna? Dibuje el DAG.</li>
<li>Cambie la referencia de <code>Fuma</code> a “Fumador” y reinterprete los coeficientes.</li>
<li>Diagnostique su modelo preferido con <code>check_model()</code> y <code>check_collinearity()</code>.</li>
</ol>
<div class="small">
<p>Próxima sesión: algoritmos de selección de variables. Después: interacciones y modificación del efecto.</p>
</div>
</section>
<section id="referencias" class="slide level2 smaller scrollable">
<h2>Referencias</h2>
<div id="refs" class="small references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-anscombe1973graphs" class="csl-entry" role="listitem">
Anscombe, F. J. 1973. <span>«Graphs in Statistical Analysis»</span>. <em>The American Statistician</em> 27 (1): 17-21. <a href="https://doi.org/10.1080/00031305.1973.10478966">https://doi.org/10.1080/00031305.1973.10478966</a>.
</div>
<div id="ref-bursac2008purposeful" class="csl-entry" role="listitem">
Bursac, Zoran, C. Heath Gauss, David Keith Williams, y David W. Hosmer. 2008. <span>«Purposeful Selection of Variables in Logistic Regression»</span>. <em>Source Code for Biology and Medicine</em> 3: 17. <a href="https://doi.org/10.1186/1751-0473-3-17">https://doi.org/10.1186/1751-0473-3-17</a>.
</div>
<div id="ref-denis2020univariate" class="csl-entry" role="listitem">
Denis, Daniel J. 2020. <em>Univariate, Bivariate, and Multivariate Statistics Using R: Quantitative Tools for Data Analysis and Data Science</em>. Hoboken, NJ: John Wiley &amp; Sons, Inc.
</div>
<div id="ref-fox2016applied" class="csl-entry" role="listitem">
Fox, John. 2016. <em>Applied Regression Analysis and Generalized Linear Models</em>. 3.ª ed. Thousand Oaks, CA: SAGE Publications.
</div>
<div id="ref-fox1992generalized" class="csl-entry" role="listitem">
Fox, John, y Georges Monette. 1992. <span>«Generalized Collinearity Diagnostics»</span>. <em>Journal of the American Statistical Association</em> 87 (417): 178-83. <a href="https://doi.org/10.1080/01621459.1992.10475190">https://doi.org/10.1080/01621459.1992.10475190</a>.
</div>
<div id="ref-greenland1999causal" class="csl-entry" role="listitem">
Greenland, Sander, Judea Pearl, y James M. Robins. 1999. <span>«Causal Diagrams for Epidemiologic Research»</span>. <em>Epidemiology</em> 10 (1): 37-48.
</div>
<div id="ref-harrell2015regression" class="csl-entry" role="listitem">
Harrell, Jr., Frank E. 2015. <em>Regression Modeling Strategies: With Applications to Linear Models, Logistic and Ordinal Regression, and Survival Analysis</em>. 2.ª ed. Cham: Springer.
</div>
<div id="ref-heinze2018variable" class="csl-entry" role="listitem">
Heinze, Georg, Christine Wallisch, y Daniela Dunkler. 2018. <span>«Variable Selection – A Review and Recommendations for the Practicing Statistician»</span>. <em>Biometrical Journal</em> 60 (3): 431-49. <a href="https://doi.org/10.1002/bimj.201700067">https://doi.org/10.1002/bimj.201700067</a>.
</div>
<div id="ref-ludecke2021performance" class="csl-entry" role="listitem">
Lüdecke, Daniel, Mattan S. Ben-Shachar, Indrajeet Patil, Philip Waggoner, y Dominique Makowski. 2021. <span>«performance: An <span>R</span> Package for Assessment, Comparison and Testing of Statistical Models»</span>. <em>Journal of Open Source Software</em> 6 (60): 3139. <a href="https://doi.org/10.21105/joss.03139">https://doi.org/10.21105/joss.03139</a>.
</div>
<div id="ref-mickey1989impact" class="csl-entry" role="listitem">
Mickey, Ruth M., y Sander Greenland. 1989. <span>«The Impact of Confounder Selection Criteria on Effect Estimation»</span>. <em>American Journal of Epidemiology</em> 129 (1): 125-37. <a href="https://doi.org/10.1093/oxfordjournals.aje.a115101">https://doi.org/10.1093/oxfordjournals.aje.a115101</a>.
</div>
<div id="ref-obrien2007caution" class="csl-entry" role="listitem">
O’Brien, Robert M. 2007. <span>«A Caution Regarding Rules of Thumb for Variance Inflation Factors»</span>. <em>Quality &amp; Quantity</em> 41 (5): 673-90. <a href="https://doi.org/10.1007/s11135-006-9018-6">https://doi.org/10.1007/s11135-006-9018-6</a>.
</div>
<div id="ref-perezguerrero2024bioestadistica" class="csl-entry" role="listitem">
Pérez Guerrero, Edsaúl Emilio. 2024. <em>Bioestadística en R para ciencias de la salud: Guía práctica</em>. 1.ª ed. Zapopan, Jalisco, México: Editorial Innovación Educativa. <a href="https://www.cucs.udg.mx/libros/lectura_cucs.php?libro=Bioestadistica_enR_digital">https://www.cucs.udg.mx/libros/lectura_cucs.php?libro=Bioestadistica_enR_digital</a>.
</div>
<div id="ref-schisterman2009overadjustment" class="csl-entry" role="listitem">
Schisterman, Enrique F., Stephen R. Cole, y Robert W. Platt. 2009. <span>«Overadjustment Bias and Unnecessary Adjustment in Epidemiologic Studies»</span>. <em>Epidemiology</em> 20 (4): 488-95. <a href="https://doi.org/10.1097/EDE.0b013e3181a819a1">https://doi.org/10.1097/EDE.0b013e3181a819a1</a>.
</div>
<div id="ref-schmidt2018linear" class="csl-entry" role="listitem">
Schmidt, Amand F., y Chris Finan. 2018. <span>«Linear regression and the normality assumption»</span>. <em>Journal of Clinical Epidemiology</em> 98: 146-51. <a href="https://doi.org/10.1016/j.jclinepi.2017.12.006">https://doi.org/10.1016/j.jclinepi.2017.12.006</a>.
</div>
<div id="ref-schneider2010linear" class="csl-entry" role="listitem">
Schneider, Astrid, Gerhard Hommel, y Maria Blettner. 2010. <span>«Linear regression analysis: part 14 of a series on evaluation of scientific publications»</span>. <em>Deutsches Ärzteblatt International</em> 107 (44): 776-82. <a href="https://doi.org/10.3238/arztebl.2010.0776">https://doi.org/10.3238/arztebl.2010.0776</a>.
</div>
<div id="ref-vanderweele2019principles" class="csl-entry" role="listitem">
VanderWeele, Tyler J. 2019. <span>«Principles of Confounder Selection»</span>. <em>European Journal of Epidemiology</em> 34 (3): 211-19. <a href="https://doi.org/10.1007/s10654-019-00494-6">https://doi.org/10.1007/s10654-019-00494-6</a>.
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Bioestadística con R · Modelos lineales — Parte 2</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>